### PR TITLE
#282 Remove All Heartbeat Logging Messages from Services

### PR DESCRIPTION
**Pull request by yanghua**
Signed-off-by: yanghua <yanghua1127@gmail.com>

cc @tsconn23

### CODE REVIEW

**Comment by feclare** [comment]
@yanghua If internal/pkg/heartbeat is no longer used remove it please.
Also you can check with ``` git grep -i heartbeat``` that there isn't  any heartbeat mention in the code or configuration files

**Comment by yanghua** [comment]
@jduranf and @feclare OK, will also remove the `internal/pkg/heartbeat`, hold on please

**Comment by yanghua** [comment]
@tsconn23 , @feclare and @jduranf waiting for reviewing~

**Comment by yanghua** [comment]
cc @jduranf

**Pull request merged**
