### PR TITLE
Enable file-token-provider in docker configuration.

### LINKED ISSUE #1677: Create Vault access tokens for different roles of EdgeX in Security-secretstore-setup
Currently all the micro services in EdgeX is utilizing master token of Vault to access credentials in Vault. It is needed to create different tokens based on different roles in Security-secretstore-setup.

### LINKED ISSUE #2265: Explictly set period and ttl for Vault tokens
# 🚀 Feature Request

### Relevant Package
security-file-token-provider

### Description
By default Vault tokens are renewable, but only up to the system maximum TTL.
In order to have long-lived tokens beyond the maximum TTL, it is necessary to specify a "periodic" parameter during the token create, which is the allowed time window in which a token can be renewed.

### Describe the solution you'd like
For all tokens created by security-file-token-provider:
Set default `ttl` to `"1h"`
Set `periodic` to `"1h"`

The above settings will ensure that tokens are indefinitely renewable so long as an active service is using them.

### Describe alternatives you've considered
Creating a periodic token is the only way in vault to have a token that is renewable indefinitely other than using the root token.

### PR DESCRIPTION
**Pull request by bnevis-i**
Add configuration to enable the file-token-provider in
the docker configuration.  Also some miscellanous fixes
to connect stdout and stderr of the child process to
the parent's file handles, and changes to the token
configuration file to sync up with existing secret
locations.

Fixes #1677 
Fixed #2265 

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

**Comment by bnevis-i** [comment]
# Testing instructions

```
make cmd/security-secretstore-setup/security-secretstore-setup
```

In developer-scripts, make the following change to `docker-compose-nexus.yml`

```
   vault-worker:
-    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go:master
+    #image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go:master
+    image: edgexfoundry/docker-edgex-security-secretstore-setup-go:master-dev
     container_name: edgex-vault-worker
     hostname: edgex-vault-worker
     networks:
@@ -144,8 +145,7 @@ services:
     volumes:
       - vault-config:/vault/config:z
       - consul-scripts:/consul/scripts:ro,z
-      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
-      - /tmp/edgex/secrets/edgex-kong:/tmp/edgex/secrets/edgex-kong:ro,z
+      - /tmp/edgex/secrets:/tmp/edgex/secrets:z
     depends_on:
       - volume
       - consul
```

Clean and restart the framework

```
docker-compose -f docker-compose-nexus.yml down -t 1 ; docker volume prune -f
docker-compose -f docker-compose-nexus.yml up -d vault-worker
```

Verify that per-service tokes are created:

```
$ sudo find /tmp/edgex -name *.json

/tmp/edgex/secrets/edgex-config-seed/secrets-token.json
/tmp/edgex/secrets/edgex-sys-mgmt-agent/secrets-token.json
/tmp/edgex/secrets/edgex-support-scheduler/secrets-token.json
/tmp/edgex/secrets/edgex-support-notifications/secrets-token.json
/tmp/edgex/secrets/edgex-support-rulesengine/secrets-token.json
/tmp/edgex/secrets/edgex-security-proxy-setup/secrets-token.json
/tmp/edgex/secrets/edgex-core-command/secrets-token.json
/tmp/edgex/secrets/edgex-mongo/secrets-token.json
/tmp/edgex/secrets/edgex-security-secretstore-setup/secrets-token.json
/tmp/edgex/secrets/edgex-core-metadata/secrets-token.json
/tmp/edgex/secrets/edgex-support-logging/secrets-token.json
/tmp/edgex/secrets/edgex-security-file-token-provider/secrets-token.json
/tmp/edgex/secrets/edgex-core-data/secrets-token.json
```

**Comment by bnevis-i** [comment]
recheck

**Comment by tingyuz** [comment]
recheck

**Comment by bnevis-i** [comment]
recheck

**Pull request merged**
