### PR TITLE
snap: miscellaneous snapcraft.yaml cleanups

### PR DESCRIPTION
**Pull request by anonymouse64**
These came out of my work on other things and aren't necessary so to make those other things more review-able, splitting these out to a separate PR.

Fixes https://github.com/edgexfoundry/edgex-go/issues/2046

### CODE REVIEW

**Comment by anonymouse64** [comment]
recheck

**Comment by bnevis-i** [comment]
If this PR is for Fuji it is now targeting the wrong branch.

**Comment by anonymouse64** [comment]
This also now fixes https://github.com/edgexfoundry/edgex-go/issues/2046

**Comment by anonymouse64** [comment]
Note that this PR has conflicts with https://github.com/edgexfoundry/edgex-go/pull/2113 (assuming that branch is cherry-picked and applied as is to master) as well as https://github.com/edgexfoundry/edgex-go/pull/2135

**Comment by bnevis-i** [comment]
Merge conflict.

**Comment by anonymouse64** [comment]
This is ready to review again

**Comment by anonymouse64** [comment]
recheck

**Pull request merged**
