### PR TITLE
Reviewed core data checks

### PR DESCRIPTION
**Pull request by jduranf**
Reviewed all core data checks related with device name and value descriptor.
Also refactored value descriptor validation checks. Now they are performed by reading and not by event, because an event can have different readings with different value descriptors.

Signed-off-by: Joan Duran <jduran@circutor.com>

### CODE REVIEW

**Comment by jduranf** [comment]
recheck

**Comment by tsconn23** [comment]
Please hold off on any more merges until tomorrow May, 22nd CST hours.

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
Related #187

**Pull request merged**
