### PR TITLE
feat: refactor services to build monolithic service easily

### PR DESCRIPTION
**Pull request by judehung**
fixes https://github.com/edgexfoundry/edgex-go/issues/5009

There is a user requirement that prefers to combine all core services into a single monolithic service. To easily achieve this based on current code structure, refactor following codes:
1. Change the signature of main function for each core services to allow pass os arguments rather than directly parse `os.Args[1:]`. With this change, the single monolithic service can alter the behavior of each individual internal services by passing different arguments.
2. Remove `os.Exit(0)` by end of a successful run of common_config_bootstrapper. This call is redundant and will force monolithic service to exit directly.

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

make build
run core-keeper, core-common-config-boostrapper, core-command, core-data, core-metadata, and ensure all bootstraps as expected.

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
please make the same change to all other services
don't limit to core services
make them consistence

**Comment by judehung** [comment]
> please make the same change to all other services don't limit to core services make them consistence

applied same changes to all edgex services in https://github.com/edgexfoundry/edgex-go/pull/5010/commits/9598f8521ec5dcf6ea01a1615061cc4ab782fe2b

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by sansmoraxz** [comment]
@judehung could you share a sample of how you have created the monolith service?

I am trying to do the same but the ports are conflicting viz. core-keeper and core-command.

**Comment by judehung** [comment]
> @judehung could you share a sample of how you have created the monolith service?
> 
> I am trying to do the same but the ports are conflicting viz. core-keeper and core-command.

@sansmoraxz please refer to https://github.com/IOTechSystems/edgex-go-low-footprint/tree/main/low-footprint/core-combo-sample#reference-implementation for reference implementation.

**Pull request merged**
