### PR TITLE
docs: Move swagger files to V3 folder

### LINKED ISSUE #4319: Move swagger files to V3 folder
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Swagger files

### Description [**REQUIRED**]
 API for 3.0.0 will be V3, so swagger files need to match

### Describe the solution you'd like
 Move swagger files to V3 folder, change version in each file to 3.0.0 and update Jenkins file to point to V3 files

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### PR DESCRIPTION
**Pull request by jinlinGuan**
Also remove unused schemas and update examples

close #4319

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) move swagger files to v3
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?) move swagger files to v3
- [ ] I have opened a PR for the related docs change (if not, why?) move swagger files to v3
  <link to docs PR>

### CODE REVIEW

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
please also update the content in the openapi/v3/README.md

**Comment by jinlinGuan** [comment]
> please also update the content in the openapi/v3/README.md

updated

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
Please replace all the apiVersion example to v3, including in the Readmee

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by lenny-intel — CHANGES_REQUESTED** [review]
> the apiVersion example to v3, including in the Readme

Correct, all instances of `v2` need to be changed to `v3`

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
