### PR TITLE
Look at Driving "Default Services List" via Configuration

### PR DESCRIPTION
**Pull request by michaelestrin**
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1662
Signed-off-by: Michael Estrin <m.estrin@dell.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/edgexfoundry/edgex-go/issues/1662

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by michaelestrin** [comment]
>  I find this ironic...

This comes across as passive-aggressive.  I'm not sure if that's what you intended.

> It seems like this change exposes some technical debit in that multiple services have service location information hard-coded into configuration files. I find this ironic since we have a component in the architecture (consul) that specializes in service location.

Service locator configuration in configuration.toml files exists prior to this PR.  It's required to support non-registry deployments.  This PR actually removes some debt -- [namely a cross-reference map in that presupposes specific service names](https://github.com/edgexfoundry/edgex-go/blob/5195c35d48ad71b067eea3de654b4993580a9db9/internal/pkg/config/types.go#L25).

@bnevis-i

**Comment by michaelestrin** [comment]
@tingyuz -- this PR has been open for a week now.  Can you please review (or let me know if I should find someone else to review it)?

**Comment by bnevis-i** [comment]
> This comes across as passive-aggressive. I'm not sure if that's what you intended. ... It's required to support non-registry deployments. 

I am sorry, that was not my intent.  I did not previously know that Consul was an optional component: I do not believe there are blackbox tests for the Consul-less configuration.  I also apologize for pulling the PR off-track.

**Comment by tingyuz** [comment]
@michaelestrin Apologize that I dropped ball here by missing the github email notification and not checking the non-security label PRs.. working on it and will get it done asap.

**Comment by tingyuz** [comment]
@michaelestrin have two questions regarding the PR: 
1. Do the behaviors of the clients need to change with this PR? 
2. is there any extra steps to verify other than running the docker-compose and verifying the system is up and working ?

**Comment by michaelestrin** [comment]
Client behavior should not change.

Change was to remove the cross-reference between internal service name (e.g. Metadata) and service's domain name (e.g. edgex-core-metadata).  

You should be able to get metrics for each service defined in the agent's configuration.toml.  

Further, you should be able to do this for both direct service and executor metrics gathering implementations.

Further, you should be able to do the aforementioned variants when running in containers as well as when running outside of them.

Since this PR updates configuration for each service to specify client information based on service domain name, each service must be tested to ensure its client usage has not been compromised.  Each service should be tested when running inside of containers as well as when running outside of them.

@tingyuz

**Comment by bnevis-i** [comment]
Michael, this PR has created a minor regression

```
level=INFO ts=2020-03-04T05:11:14.75532179Z app=edgex-support-scheduler source=bootstrap.go:133 msg="Loaded configuration from http://edgex-core-consul:8500"
parse ://:0/api/v1/logs: missing protocol scheme
parse ://:0/api/v1/logs: missing protocol scheme
level=INFO ts=2020-03-04T05:11:14.755831345Z app=edgex-support-scheduler source=registry.go:49 msg="Using Registry from http://edgex-core-consul:8500"
level=INFO ts=2020-03-04T05:11:14.757286258Z app=edgex-support-scheduler source=config.go:138 msg="Writeable configuration has been updated from the Configuration Provider"
parse ://:0/api/v1/logs: missing protocol scheme
level=INFO ts=2020-03-04T05:11:14.854591951Z app=edgex-support-scheduler source=client.go:75 msg="ttl already <= half of the renewal period"
parse ://:0/api/v1/logs: missing protocol scheme
level=INFO ts=2020-03-04T05:11:14.867203718Z app=edgex-support-scheduler source=database.go:144 msg="Database connected"
parse ://:0/api/v1/logs: missing protocol scheme
level=INFO ts=2020-03-04T05:11:14.869942286Z app=edgex-support-scheduler source=loader.go:38 msg="loading intervals, interval actions ..."
parse ://:0/api/v1/logs: missing protocol scheme
```

It seems to originate in go-mod-bootstrap:
go-mod-bootstrap that references bootstrapConfig.Clients["Logging"].Url()

Essentially, there is an error building the logging server URL.

**Comment by michaelestrin** [comment]
@bnevis-i Thank you for catching this.  I'll spin several issues to address this problem.

**Pull request merged**
