### PR TITLE
refactor: Assign/use new Port assignments

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?
Ports assigned are in the 408xx range

## What is the new behavior?
Ports assigned are now in the 588xx range
All instances of old port number have been update to use the new port numbers.

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

BREAKING CHANGE: Core/Support/SysMgmt default ports numbers have changed.

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by lenny-intel** [comment]
recheck

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
the v1 API document in openapi/v1/ folder should not be changed

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
> the v1 API document in openapi/v1/ folder should not be changed

@cloudxxx8 , Yea, it got caught with the global replace. Left the changes since it will be removed soon anyways.

**Comment by cloudxxx8** [comment]
@lenny-intel it will be automatically pushed to SwaggerHub, so it might impact the existing 1.x users.
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.1

**Comment by lenny-intel** [comment]
Crud!!! You are correct! I verified changes did get published. Will file issue and fix.

**Comment by lenny-intel** [comment]
@cloudxxx8 Fixed

**Pull request merged**
