### PR TITLE
refactor!: Use bool types for command parameters to be more consistent

### PR DESCRIPTION
**Pull request by jinlinGuan**
BREAKING CHANGE: ds-pushevent and ds-returnevent to use bool true/false instead of yes/no
    
related: https://github.com/edgexfoundry/go-mod-core-contracts/pull/782
    
Signed-off-by: Ginny Guan <ginny@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
https://github.com/edgexfoundry/edgex-docs/pull/917 and the core-command Swagger file in this repo

## Testing Instructions

build core-command and device-virtual docker images based on the changes and run docker-compose.yml
The following commands work as expected:
```
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=true
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=false
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-return\=true
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-return\=false
```
and the following commands return errors as expected:
```
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=yes
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=no
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-return\=yes
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-return\=no
```

### CODE REVIEW

**Comment by cloudxxx8** [comment]
please modify the Swagger file as well

**Comment by bnevis-i** [comment]
@jinlinGuan  Go mod changes are propagated; marking ready for review.

**Review by bnevis-i — APPROVED** [review]

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
@cloudxxx8 Do you think we could merge this one and do the swagger in a followup PR?   The breaking change not merged is holding me up on my security work.

**Comment by jinlinGuan** [comment]
The core-command Swagger file has already been updated in this PR. 

> @cloudxxx8 Do you think we could merge this one and do the swagger in a followup PR? The breaking change not merged is holding me up on my security work.

**Pull request merged**
