### PR TITLE
export-client: Fix getting no registrations from memorydb

### PR DESCRIPTION
**Pull request by feclare**
It was returning null instead of empty array when a registration was never added.

### CODE REVIEW

**Comment by feclare** [comment]
I'm not sure, but I should tell that it is not the case. In data y metadata I used a different approach when getting all the items in one table.

**Comment by jduranf** [comment]
@feclare, I checked this issue it's present in core-data. Should be fine to fix it in another PR

**Comment by feclare** [comment]
@jduranf Thanks for the test. 
I think I will add the fix to this PR as it is the same error.

**Comment by tsconn23** [comment]
@feclare @jduranf Do we have an issue for what's being addressed here? If so, can you link it in the PR comment above?

**Pull request merged**
