### PR TITLE
Fix bug wherein we get a Go panic on starting the SMA in a docker container.

### PR DESCRIPTION
**Pull request by akramtexas**
- Fix bug wherein we get a Go-runtime-emitted panic on starting the SMA in a docker container (Things work great outside of Docker, on a Linux box).
- The relevant issue is: [Issue #624](https://github.com/edgexfoundry/edgex-go/issues/624)

### CODE REVIEW

**Comment by tsconn23** [comment]
@akramtexas Please resolve the file conflict as well. Thx.

**Comment by akramtexas** [comment]
@tsconn23 Yep, I'm resolving the file conflict at the moment (It's odd, but the conflict did not show up until much later).

**Comment by akramtexas** [comment]
@anonymouse64 To clarify, I'm currently testing the fix, but I reckoned that it didn't hurt to open a PR (since I hadn't added any reviewers). Although I notice that you self-assigned yourself. That's OK (And sorry for the confusion). But please wait until further notice before retesting, thanks @tsconn23 
- To cut a long story short, the reason I had opened a PR has to do with testing the fix in a containerized environment. Previously, I had been using **docker-compose** (and not docker directly) for working with containers locally. But the Makefile, I realize, and recall, that doesn't look like it uses local images. So I'll be using docker directly to start the containers manually for now locally.

**Comment by anonymouse64** [comment]
@akramtexas the only reason I assigned myself to that issue is because the original issue is just to add the sys-mgmt-agent to the snap, not the crashing bug but the issue now tracks both things so ... :man_shrugging: 

I'll hold off on more testing for now then

**Comment by akramtexas** [comment]
@anonymouse64 
- It's all good, no worries whatsoever on assigning yourself to that issue.
- In fact, I was debating whether to open a _new_ issue or re-use this one, and opted in favor of using the minimal issue-tracking activity that made sense to me 😄 
- On the other hand, conflating related issues has some of it's own drawbacks, I confess 🎋 
- OK, cool, please do hold off on more testing for now 👍

**Comment by akramtexas** [comment]
@anonymouse64 
- Further testing needs to be done (on my end) so please continue to hold off on more testing for now (until I give the word), thanks.
- Initial testing is encouraging, as there is no panic on starting the SMA in Docker container:

> Akrams-MacBook-Pro:edgex-go akramahmad$ docker logs 3db9a299019e79ac436f4756a4bd0ddeb450502529721c615951d5c70ff26a67
Creating directory: /edgex/logs
INFO: 2018/10/31 18:28:44 Service dependencies resolved...
INFO: 2018/10/31 18:28:44 Starting edgex-sys-mgmt-agent 0.7.0 
INFO: 2018/10/31 18:28:44 This is the System Management Agent Service
INFO: 2018/10/31 18:28:44 Service started in: 1.6605ms
INFO: 2018/10/31 18:28:44 Listening on port: 48090

> Akrams-MacBook-Pro:edgex-go akramahmad$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
0b1ffc66de61        565b781a6eff        "/sys-mgmt-agent --p…"   10 minutes ago      Up 10 minutes                           elated_johnson

**Comment by akramtexas** [comment]
@anonymouse64 
- A heads up at this time (I'm continuing to test the fix for this issue) that, **once I confirm that testing is all good on my end**, you'll also need to make a corresponding update to your Snapcraft file(s), corresponding to my removing the flag --consul from Dockerfile.sys-mgmt-agent. [More details here, FWIW, on the Docker side of things](https://github.com/akramtexas/edgex-go/commit/3b5ea0702beda656640a8a4eba32af85708b8956).

**Comment by akramtexas** [comment]
@tsconn23 I'm looking this second into whether a **git squashing of commits** is warranted...

**Comment by akramtexas** [comment]
@tsconn23 Done (I followed up, and this is to confirm that **two commits have been squashed** and the resulting delta pushed, triggering hopefully the _final_ build checks for this PR) 😄 Also, thanks again for the pointers on testing the deployment to Docker containers locally 👍

**Comment by akramtexas** [comment]
@anonymouse64 
- That is exactly right: You are seeing expected behavior (The SMA, aka sys-mgmt-agent, is designed to operate independently, in a stand-alone fashion. In particular, the SMA should not rely on Consul, and leaving the --consul flag, as was _originally_ the case (but now corrected by updating the relevant Docker file), was an oversight on my part).

- So yes, **please remove the --consul flag** (in Snapcraft) as mentioned here: [Comment](https://github.com/edgexfoundry/edgex-go/pull/727#issuecomment-435095867) 👍

**Comment by akramtexas** [comment]
Meanwhile, looks like I need to rebase again: Doing that this moment ⌛️

**Comment by anonymouse64** [comment]
@akramtexas I still think that if the sys-mgmt-agent is intended to support using consul at some point in the future, but doesn't do so now, it should fail or return a "pretty" error, etc. rather than panic'ing. As such, I'll leave my review requesting changes until either folks decide it's fine and ignore my review, or until something more sensible happens the `--consul` flag is used.

**Comment by akramtexas** [comment]
@anonymouse64 After following up on what the next steps should be, here is the direction going forward: 
- Because the SMA is designed to operate independently, in a stand-alone fashion, and in particular, the SMA should _not_ rely on Consul, removal of the --consul flag (in the relevant Docker file) will remain as-is.
- Additionally, the SMA code will be updated so as to no longer deal with accepting the "--consul" aka "--c" flag) due to the reasons above.

**Comment by akramtexas** [comment]
@tsconn23 Testing (locally) with Docker containers is under way. Will update once that is complete.

**Comment by akramtexas** [comment]
- The ARM build check is running (**other three have passed**).
- Rebasing (with upstream Delhi branch) remains up-to-date.
- I have **wrapped up testing**, with results confirming that the (following) update works:
`Remove code having to do with accepting the --consul" flag. Add code to set the useConsul variable to false since we no longer handle the --consul flag.`
- As before, hitting the SMA's end point each for api/v1/config and api/v1/metrics was successful.
- As before, the SMA started normally and stayed up throughout testing: 
> Akrams-MacBook-Pro:compose-files akramahmad$ docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.RunningFor}}"
NAMES                             STATUS                      PORTS                                                                                                            CREATED
edgex-export-distro               Up 14 minutes               0.0.0.0:5566->5566/tcp, 0.0.0.0:48070->48070/tcp                                                                 14 minutes ago
.............................................................................................................................................................................................
.............................................................................................................................................................................................
edgex-support-logging             Up 14 minutes               0.0.0.0:48061->48061/tcp                                                                                         14 minutes ago
edgex-config-seed                 Exited (0) 14 minutes ago                                                                                                                    14 minutes ago
edgex-core-consul                 Up 14 minutes               0.0.0.0:8400->8400/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp, 8300-8302/tcp, 8600/udp, 0.0.0.0:8600->8600/tcp   14 minutes ago
edgex-mongo                       Up 14 minutes               0.0.0.0:27017->27017/tcp                                                                                         14 minutes ago
edgex-sys-mgmt                    Up 14 minutes               0.0.0.0:48090->48090/tcp                                                                                         14 minutes ago

**Comment by akramtexas** [comment]
👍

**Pull request merged**
