### PR TITLE
[WIP] Simplify Makefile

### PR DESCRIPTION
**Pull request by drasko**
- List of targets is more logical
- Use BUILD_DIR to output binaries
- `clean` target is simpler (removes whole build dir)

Signed-off-by: Drasko DRASKOVIC <drasko.draskovic@gmail.com>

### CODE REVIEW

**Comment by drasko** [comment]
Alas, I have just noticed that https://github.com/edgexfoundry/edgex-go/issues/26 blocks this PR.

Should not be merged until this issue is resolved.

**Comment by drasko** [comment]
@jpwhitemn @janko-isidorovic @tsconn23 please do not merge this one yet. We have to see can the binaries be moved to `build` dir during compilation, and how to handle hard-coded config file path.

Probably Makefile will have to move the configs and put them on our `build` or `release` directory during the compilation, so we can then easily move the whole package from one computer to another.

**Comment by JPWKU** [comment]
recheck

**Comment by drasko** [comment]
@tsconn23 I will take a look at it and propose resolution.

**Comment by drasko** [comment]
Dropping this PR for now, not a priority. I will align later when we have clearer picture of where binaries actually have to go.

**Pull request closed without merging**
