### PR TITLE
build: Upgrade to go 1.18 and latest golangci-lint

### PR DESCRIPTION
**Pull request by lenny-intel**
Fixed issue flag by latest linter

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **N/A**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
Run the following make commands:

- make tidy
- make build
- make test
- make docker

### CODE REVIEW

**Review by farshidtz — APPROVED** [review]

**Comment by farshidtz** [comment]
Thanks for the changes. I've verified the snap changes.

Jenkins builds are failing for both arm64 and amd64:
```
ERROR: for security-spiffe-token-provider  (<Service: security-spiffe-token-provider>, "The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init curl gcompat' returned a non-zero code: 2")
ERROR: for security-spire-agent  (<Service: security-spire-agent>, "The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init openssl gcompat' returned a non-zero code: 1")
ERROR: for security-spire-server  (<Service: security-spire-server>, "The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init openssl gcompat' returned a non-zero code: 1")
Service 'security-spire-server' failed to build: The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init openssl gcompat' returned a non-zero code: 1
```

**Comment by bnevis-i** [comment]
> Thanks for the changes. I've verified the snap changes.
> 
> Jenkins builds are failing for both arm64 and amd64:
> 
> ```
> ERROR: for security-spiffe-token-provider  (<Service: security-spiffe-token-provider>, "The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init curl gcompat' returned a non-zero code: 2")
> ERROR: for security-spire-agent  (<Service: security-spire-agent>, "The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init openssl gcompat' returned a non-zero code: 1")
> ERROR: for security-spire-server  (<Service: security-spire-server>, "The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init openssl gcompat' returned a non-zero code: 1")
> Service 'security-spire-server' failed to build: The command '/bin/sh -c apk update && apk --no-cache --update add dumb-init openssl gcompat' returned a non-zero code: 1
> ```

Lenny mentioned this yesterday.  It appears as of the nl.alinelinux.org mirror is inconsistent.  I checked yesterday to make sure the site is still getting updates, and it is, but apparently it is not being uniformly updated.

I checked the Alpine mirror list and it appears as if nl.alpinelinux.org is no longer listed.  Instead, `dl-4` seems to have replaced it and it works fine.  If I recall, we don't use `dl-cdn` because some of the mirrors have IP address reputation problems that are blocked by corporate firewalls occasionally.

My proposal is to replace `nl.alpinelinux.org` with `dl-4.alpinelinux.org` in our Dockerfiles.

**Comment by bnevis-i** [comment]
> My proposal is to replace `nl.alpinelinux.org` with `dl-4.alpinelinux.org` in our Dockerfiles.


See https://github.com/edgexfoundry/edgex-go/pull/4069 for the fix.

**Review by bnevis-i — APPROVED** [review]
LTGM.  Will work better after merging the mirror update in.

**Review by bill-mahoney — DISMISSED** [review]
LGTM

**Review by jim-wang-intel — APPROVED** [review]

**Review by ernestojeda — COMMENTED** [review]
I will coordinate the Go 1.18 CI base image so it is ready when we merge this PR

**Comment by lenny-intel** [comment]
> Will work better after merging the mirror update in.

Rebased.

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
