### PR TITLE
docs(all): update Changelog for Kamakura

### PR DESCRIPTION
**Pull request by jpwhitemn**
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) n/a
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?) n/a
- [ ] I have opened a PR for the related docs change (if not, why?) n/a
  <link to docs PR>

### CODE REVIEW

**Review by farshidtz — CHANGES_REQUESTED** [review]
@jpwhitemn Thanks for the changelog. Do you use a tool to generate the changelogs? It's missing some snap features in Kamakura and Jakarta. 

E.g for Kamakura: https://github.com/edgexfoundry/edgex-go/pull/3986

Not sure if other scopes are affected too.

**Comment by jpwhitemn** [comment]
> @jpwhitemn Thanks for the changelog. Do you use a tool to generate the changelogs? It's missing some snap features in Kamakura and Jakarta.
> 
> E.g for Kamakura: #3986
> 
> Not sure if other scopes are affected too.

@bill-mahoney - can you get with Farshid on what items seem to be missing and whether these just need to be added by hand.
@farshidtz - we do have a tool that generates these and then we manually remove some of the items that would not be of concern to end users/adopters.

**Review by farshidtz — APPROVED** [review]
Thanks @jpwhitemn for the updates.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
