### PR TITLE
feat(security): Add configuration for CodeQL static analysis

### LINKED ISSUE #3593: Enable CodeQL static analysis for edgex-go
CodeQL has been enabled on a trial basis for app-functions-sdk-go but it has found little so far.

I would like to expand the pilot to edgex-go to see if it can actually find anything notable.

Approved as part of Jakarta planning

### PR DESCRIPTION
**Pull request by bnevis-i**
Fixes #3593

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?
Add configuration files to enable CodeQL static analysis

## Issue Number:
Closes #3593

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## New Imports

- [ ] Yes
- [X] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by bnevis-i** [comment]
@rsdmike  I copied this configuration from app-functions-sdk-go.  Does this look right?

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by rsdmike** [comment]
For CodeQL, you only need the first one --  `.github/workflows/codeql-analysis.yml `.  The second one `.github/workflows/go.yml` is for adding the build to github actions, not sure if that is what you are after.  Either case, LGTM.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
