### PR TITLE
Added management client to fetch microservices configuration and metrics

### LINKED ISSUE #680: Inconsistent URL path usage in pkg/clients/notifications
PR #620 added two functions in pkg/clients/notifications, FetchConfiguration() and FetchMetrics(). The problem of this two functions is they expect to have an empty URL path when the client is set, but SendNotification() expect to have a defined URL path.

To be more clear, this is how is defined the notifications client in core-metadata:
```
	// Create notification client
	params := types.EndpointParams{
		ServiceKey:  internal.SupportNotificationsServiceKey,
		Path:        clients.ApiNotificationRoute,
		UseRegistry: useConsul,
		Url:         Configuration.Clients["Notifications"].Url() + clients.ApiNotificationRoute,
		Interval:    Configuration.Service.ClientMonitor,
	}

	nc = notifications.NewNotificationsClient(params, startup.Endpoint{})
```

And this is how is defined in the sys-mgmt-agent:
```
	// Create notification client
	params := types.EndpointParams{
		ServiceKey:  internal.SupportNotificationsServiceKey,
		Path:        "/",
		UseRegistry: useConsul,
		Url:         Configuration.Clients["Notifications"].Url(),
		Interval:    internal.ClientMonitorDefault,
	}

	nc = notifications.NewNotificationsClient(params, startup.Endpoint{})
```

If the client is defined like in core-metadata, SendNotification() will work but FetchConfiguration() and FetchMetrics() will fail. But if the client is defined like in sys-mgmt-agent, SendNotification() will fail and FetchConfiguration() and FetchMetrics() will work.

There are two ways to fix this issue, modify core-metadata in order to work using an empty URL path, or split this client in two.
@akramtexas and @tsconn23, what do you think?

### PR DESCRIPTION
**Pull request by jduranf**
This should fix #680.
Also this client can be used in #672.

Signed-off-by: Joan Duran <jduran@circutor.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
@jduranf This is a good pattern. The only gripe I have is putting the client in the client/mgmt package. The packages under client are each clients to use when accessing the specific service (metadata, coredata and so on). In this case it's not a client used to access mgmt, but a client used BY mgmt to access other services. I admit I don't have a better suggestion for the placement right now. Maybe something like /pkg/clients/general? Perhaps I'm being too picky.

**Comment by jduranf** [comment]
@tsconn23 although /pkg/clients/general doesn't sounds nice for me, I agree with you that using /pkg/clients/mgmt is confusing and I don't have any better suggestion than /pkg/clients/general, so I changed as you suggested

**Comment by akramtexas** [comment]
@jduranf Reviewing the pattern for potential use in my MSM work, thanks for your effort. While doing so, noticed that the ARM build check has failed, FYI.

**Comment by jduranf** [comment]
recheck

**Comment by akramtexas** [comment]
@jduranf Looking at the console output of the failed build, I noticed:

> 08:45:16 Error response from daemon: conflict: unable to delete c225776ced97 (cannot be forced) - image has dependent child images

**Comment by jduranf** [comment]
@akramtexas PR #689 also is failing with the same error, so seems to be a problem with arm check... @JPWKU can you check it?

**Comment by tsconn23** [comment]
recheck

**Comment by anonymouse64** [comment]
@jduranf @JPWKU the issue appears to be due to a newer dependency: 
```
09:16:34 pyopenssl 18.0.0 has requirement cryptography>=2.2.1, but you'll have cryptography 2.1.4 which is incompatible.
09:16:34   The script chardetect is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:34   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:35   The script pbr is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:35   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:36   The script lftools is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:36   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:38   The script pybabel is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:38   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:41   The script swift is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:41   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:45   The script openstack-inventory is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:45   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:46   The script heat is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:46   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:47   The script nova is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:47   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:48   The script cinder is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:48   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:48   The script jsonschema is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:48   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:49   The script glance is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:49   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:49   The scripts oslo-config-generator and oslo-config-validator are installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:49   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
09:16:53   The script openstack is installed in '/home/jenkins/.local/bin' which is not on PATH.
09:16:53   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

I think that all the script warnings can be ignored but the cryptography pip package version being incompatible causes it to fail to finish:


```
09:16:55 + pip freeze
09:16:55 Traceback (most recent call last):
09:16:55   File "/usr/bin/pip", line 9, in <module>
09:16:55     from pip import main
09:16:55 ImportError: cannot import name main
```

**Comment by JPWKU** [comment]
I am looking into this now.

**Comment by akramtexas** [comment]
@jduranf Your code updates LGTM 👍 Looking forward to the CI/CD pipeline issue being resolved.

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Pull request merged**
