### PR TITLE
Fix for missing comma in docker configuration file (failed to parse)

### PR DESCRIPTION
**Pull request by SteveOss**

### CODE REVIEW

**Comment by drasko** [comment]
@SteveOss please sign-off your commits, needed for DCO.

**Comment by SteveOss** [comment]
@drasko Is there a way of post applying a sign-off to this pull request ?

**Comment by drasko** [comment]
@SteveOss you can try at `git commit -s --amend`, then `push -f origin master` on your fork. It will automatically update the PR.

**Comment by feclare** [comment]
@SteveOss 
Having some merges from master I don't think you can fix your commit with --ammend. Maybe it is easier to create a new PR

**Comment by tsconn23** [comment]
Closing this PR as I have replaced it with PR #66. @feclare please review and merge when you have a moment.

**Pull request closed without merging**
