### PR TITLE
Bugfix core-data "get event by deviceId" api return no data

### PR DESCRIPTION
**Pull request by unanao**
API:   http://localhost:48080/api/v1/event/device/:deviceId/:limit
Error: no data returned:
Reason: As mongoEvent not match mongodb's structure(models.Event)

### CODE REVIEW

**Comment by jduranf** [comment]
@unanao, the events are stored as mongoEvent. Why this patch should solve the issue?

**Comment by tsconn23** [comment]
Commit isn't signed. No issue created for this PR. Testing this PR against master for the following URL literally produces no difference in behavior.

http://localhost:48080/api/v1/event/device/KMC.BAC-121036CE01/5

Testing methodology included `make run` followed by running device-virtual service.

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by unanao** [comment]
I pulled the latest code, the bug not exist

**Pull request closed without merging**
