### PR TITLE
Centralized several API routes

### PR DESCRIPTION
**Pull request by jduranf**
Fix partially #703 

Signed-off-by: Joan Duran <jduran@circutor.com>

### CODE REVIEW

**Comment by jduranf** [comment]
ok!

**Comment by jduranf** [comment]
@tsconn23 I just remeber that this PR also fixes an issue in support-logging. As you can [see](https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/logging/server.go#L262), `replyPing` handler is declared twice:

```go
// Ping Resource
mux.Get(clients.ApiPingRoute, http.HandlerFunc(replyPing))

// Configuration
mux.Get(clients.ApiConfigRoute, http.HandlerFunc(replyConfig))

// Metrics
mux.Get(clients.ApiMetricsRoute, http.HandlerFunc(replyMetrics))
mv1 := mux.Prefix("/api/v1")

mv1.Get("/ping", http.HandlerFunc(replyPing))
```

I don't know which will be the behaviour, but I think it should be fixed

**Comment by tsconn23** [comment]
@jduranf OK, we're back from the face to face meeting now so I can start looking at PRs. Can you update your branch and resolve the conflict above? Then we should be able to get this one in.

**Comment by jduranf** [comment]
rebased and the conflict have been resolved

**Pull request merged**
