### PR TITLE
fix:do not delete redis keys of schedule completely

### PR DESCRIPTION
**Pull request by worldmaomao**

### CODE REVIEW

**Comment by michaelestrin** [comment]
@AnthonyMBonafide please see comments in prior related PR when reviewing this one.  https://github.com/edgexfoundry/edgex-go/pull/2254

**Comment by AnthonyMBonafide** [comment]
I also verified that these changes work when rebased with the latest changes from master, the tip of master at the point of testing was `45301cbd-7057-4974-9f38-7d0e356fed3f`. It is safe to update branch from that point.

**Comment by michaelestrin** [comment]
recheck

**Comment by michaelestrin** [comment]
recheck

**Comment by michaelestrin** [comment]
recheck

**Pull request merged**
