### PR TITLE
fix(data):Correct GetEventById V2 implementation

### PR DESCRIPTION
**Pull request by cloudxxx8**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2719

## What is the new behavior?
Fix the bugs in GetEventById V2 API:
- store Event and Reading with the collection prefix
- query Readings when getting Event

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
rebased from master

**Comment by cloudxxx8** [comment]
recheck

**Review by judehung — APPROVED** [review]
LGTM

**Pull request merged**
