### PR TITLE
feat(security): add security.txt to docker images (#4407)

### LINKED ISSUE #4151: Support security.txt standard for Docker images
## Feature request

Build docker images with a security.txt in them.

https://securitytxt.org/

This is a standard metadata structure to communicate how to report security vulnerabilities.

### PR DESCRIPTION
**Pull request by geraldzm**
Closes #4151 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

run `make docker`

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Review by bnevis-i — APPROVED** [review]

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@bnevis-i , looks like a few of the security services are missing the Attribution file copied into the docker file. Please add an issue to your board to correct this. THX!

**Comment by bnevis-i** [comment]
> @bnevis-i , looks like a few of the security services are missing the Attribution file copied into the docker file. Please add an issue to your board to correct this. THX!

👌

**Pull request merged**
