### PR TITLE
Update to latest go-mod-messaging

### LINKED ISSUE #2339: Update go-mod-messaging dependency; Integrate new MQTT implementation
From https://github.com/edgexfoundry/go-mod-messaging/issues/36#issuecomment-581957508

### PR DESCRIPTION
**Pull request by AnthonyMBonafide**
Fix #2339

Update to use the latest version of `go-mod-messaging` so we can
leverage the newly added functionality for MQTT support.

Update the existing `MessageQueueInfo` struct to include an `Optional`
field where additional configuration information can be passed into the
underlying client constructor. This new field is meant to facilitate
additional configurations that do not fit into the existing fields.

Update core data to pass the new `Optional` field to the client
constructor.

Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
The configuration properties are passed to the client constructor in `go-mod-messaging`. The version being used prior to these changes only allow for ZeroMQ clients. Also we are not passing and "Optional" configuration properties, which was not an issue until now where `go-mod-messaging` supports multiple clients some which might rely on the "Optional" information.

Issue Number: #2339

## What is the new behavior?
Configuration can be read from a field "Optional" which gives the user a chance to give additional configuration information. The "Optional" information is new being passed to the client constructor via the `MessageBusConfig.Type`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any specific instructions or things that should be known prior to reviewing?

To manually verify these changes use the following TOML snippet as a starting point:
```toml
[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'
Type = 'mqtt'
Topic = 'events'
  [MessageQueue.Optional]
    Username          = "TestUsername"
    Password          = "TestPassword"
    ClientId          = "TestClientId"
    Topic             = "TestTopic"
    Qos               = "1"
    KeepAlive         = "30"
    Retained          = "false"
    ConnectionPayload = "TestConnectionPayload"
```

start `core-data`(Possibly with a breakpoint at https://github.com/AnthonyMBonafide/edgex-go/blob/745920f1c5422c71e217115a6a36714e56c09258/internal/core/data/init.go#L93) to ensure the data was properly read and parsed.

## Other information

### CODE REVIEW

**Comment by lenny-intel** [comment]
Issue # that this addresses needs to be added to above PR description. Also does your commit message follow the Guidelines? If not, it should be adjust to do so.

**Comment by AnthonyMBonafide** [comment]
> Issue # that this addresses needs to be added to above PR description. Also does your commit message follow the Guidelines? If not, it should be adjust to do so.

Updated. Sorry, that is my first time seeing that message added like that.

**Comment by AnthonyMBonafide** [comment]
I verified these changes with blackbox tests, unit tests, and manually by updating the configuration and inspecting the resulting client for the correct type and configuration properties.

**Comment by michaelestrin** [comment]
@AnthonyMBonafide @lenny-intel 

Are there any documentation or configuration.toml changes that need to be made as part of these changes?  How would someone know to modify the configuration.toml in the described way (beyond looking at this PR's comments)?

**Comment by AnthonyMBonafide** [comment]
> @AnthonyMBonafide @lenny-intel
> 
> Are there any documentation or configuration.toml changes that need to be made as part of these changes? How would someone know to modify the configuration.toml in the described way (beyond looking at this PR's comments)?

Good point, would it be reasonable to link to the documentation in `go-mod-messaging` in `core-data` `configuration.toml`? For example:

```toml

# Configuration for message client.
# For more detailed configuration options please see the README document in go-mod-messaging(https://github.com/edgexfoundry/go-mod-messaging/blob/master/README.md#how-to-use)
[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'
Topic = 'events'
```

**Comment by lenny-intel** [comment]
> @AnthonyMBonafide @lenny-intel
> 
> Are there any documentation or configuration.toml changes that need to be made as part of these changes? How would someone know to modify the configuration.toml in the described way (beyond looking at this PR's comments)?

I am not aware of any for Core Data, but for App Functions, we have the README that should be updated when that PR is done.

**Comment by michaelestrin** [comment]
> would it be reasonable to link to the documentation in `go-mod-messaging` in `core-data` `configuration.toml`?

What do you think @lenny-intel?  

As context, think of the person modifying configuration as somewhat technical but has no knowledge of Golang, go-mod-messaging, or how the system is put together.  They're just trying to find a document or reference for configuring the system to turn this new MQTT capability on.

I would think we've run into this sort of thing already with go-mod-secrets, go-mod-registry, go-mod-configuration and the like.  How do we address these documentation concerns today?  If we don't, what is a reasonable approach we can generally standardize on going forward?

**Comment by lenny-intel** [comment]
> I would think we've run into this sort of thing already with go-mod-secrets, go-mod-registry, go-mod-configuration and the like. How do we address these documentation concerns today? If we don't, what is a reasonable approach we can generally standardize on going forward?

Personally, I think the Configuration section in the edgex-docs should cover all the sections in the services' configurations. I don't see this documented anywhere. This is a good topic to bring up in the next architects meeting. In the meantime I think @AnthonyMBonafide solution will suffice for Core Data.

**Comment by michaelestrin** [comment]
@jpwhitemn 

Please see discussion above regarding a reasonable and standard approach to document variations in configuration (usually specifying a concrete implementation for a contract specified and satisfied by a module external to the service).

@lenny-intel has recommended this be discussed/resolved at the next architect's meeting.

**Pull request merged**
