### PR TITLE
fix: take out parallel running in unit tests to avoid timing issue

### PR DESCRIPTION
**Pull request by jim-wang-intel**
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
recheck

**Comment by jim-wang-intel** [comment]
recheck

**Comment by jim-wang-intel** [comment]
> recheck

for i in {1..5}; do recheck; done ; :->

**Review by bnevis-i — APPROVED** [review]

**Pull request merged**
