### PR TITLE
#64 [support][logging] fixed error content-type for ping request

### PR DESCRIPTION
**Pull request by yanghua**
Signed-off-by: yanghua <yanghua1127@gmail.com>

see issue #64 

cc @drasko

### CODE REVIEW

**Comment by chenchix** [comment]
See my comment in the issue you have just opened.

If  you open an issue, wait for comments before push the PR :)

**Comment by yanghua** [comment]
@chenchix  OK, I will change it to json format.

**Comment by yanghua** [comment]
@chenchix done this, I create a issue and make a PR because it's a obviously error. If this is a ambiguity issue, I will wait for answering.

**Comment by chenchix** [comment]
No problem. :)

**Pull request merged**
