### PR TITLE
Refactoring toward external/internal packages -- Part A

### PR DESCRIPTION
**Pull request by tsconn23**
#368 

This PR is mainly focused on reorganizing the code.  It does NOT yet address the separation of the domain model into internal/external. I think this is enough in one shot. Please see the comment I just left on the issue above for information about where this is heading.

- Moved the service directories out of edgex-go/core and moved them to edgex-go/internal/core.
- Moved edgex-go/core/db to edgex-go/internal/pkg/db
- Updated any import statements where necessary
- Validated all changes via "make test" and local blackbox testing
- No functional changes have been made at all. This is a re-organization only.

### CODE REVIEW

**Comment by tsconn23** [comment]
@JPWKU Docs-verify is failing because of the error below. The path doesn't exist anymore so we need to adjust the script. Let's discuss on Monday.

```
[edgex-go-docs] $ /bin/sh -xe /tmp/jenkins6799755749349068922.sh
+ cd docs/
+ ./build.sh
cp: cannot stat â€˜../core/data/raml/*.ramlâ€™: No such file or directory
Build step 'Execute shell' marked build as failure
```

**Comment by JPWKU** [comment]
@tsconn23 Looks like we will need to adjust `docs/build.sh`.  The `cp` commands on the raml files are failing.  If we updated those to the new location I think we will be good.

**Comment by tsconn23** [comment]
@JPWKU Updated PR. The location of the RAML files that used to be in /edgex-go/core as of this PR will be edgex-go/external/raml. That means the three in this list:

- edgex-go/core/command/raml/core-command.raml
- edgex-go/core/data/raml/core-data.raml
- edgex-go/core/metadata/raml/core-metadata.raml

Please modify the `docs/build.sh` script

**Comment by JPWKU** [comment]
recheck

**Pull request merged**
