### PR TITLE
fix: Tweaks to Core Common Config Docker and entrypoint script for secure mode

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **N/A**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
See follow on edgex-compose PR

### CODE REVIEW

**Review by jim-wang-intel — COMMENTED** [review]
IMO, this way loses the ability to override the extra cmd paramters only without specifying the original entrypoint.sh. e.g. you could just specify command: ["/core-common-cofnig", "param1", "param2",...etc]  without touching entrypioint.

**Comment by lenny-intel** [comment]
> IMO, this way loses the ability to override the extra cmd paramters only without specifying the original entrypoint.sh. e.g. you could just specify command: ["/core-common-coifing", "param1", "param2",...etc] without touching entrypioint.

Nope, that doesn't work. We need the local entry point script to run from the bootstrap entrypoint script . Only other way would be to create a new security bootstrap entrypoint script specify for this service like we do for proxy setup. IMO this is cleaner than creating another one off security script. This service doesn't need flexibility to override parameters as it has a very narrow purpose.

**Review by bnevis-i — COMMENTED** [review]
The way we have done this in all the other Dockerfiles is that the executable is in ENTRYPOINT (in this case, entrypoint.sh), and the arguments are in CMD.

**Comment by lenny-intel** [comment]
> The way we have done this in all the other Dockerfiles is that the executable is in ENTRYPOINT (in this case, entrypoint.sh), and the arguments are in CMD.

Yes that is the standard way, but this case we have two entry point scripts that need to be run and is the original approach we used and works in non-secure...

I think I found a way to override the `command` in the  secure compose where is calls the local entrypoint and passes the command..
```
    command:
    - /entrypoint.sh
    - /core-common-config-bootstrapper
    - -cp=consul.http://edgex-core-consul:8500
```
This is working but was hand edited...
Will close this PR once verify I can get that to be generated properly.

**Comment by lenny-intel** [comment]
Yep, that worked! Closing this PR

**Pull request closed without merging**
