### PR TITLE
feat: Add persisting of new Tags property on V1 & V2 Event models for Redis

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

New Tags property on V1 & V2 models not persisted to Redis DB

Issue Number: #2668

## What is the new behavior?

New Tags property on V1 & V2 models is now persisted to Redis DB

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?

no

### CODE REVIEW

**Comment by cloudxxx8** [comment]
We updated DeviceClient in https://github.com/edgexfoundry/go-mod-core-contracts/pull/273 , so the mocks.DeviceClient needs to be updated to pass the unit test

**Comment by lenny-intel** [comment]
> mocks.DeviceClient needs to be updated to pass the unit test

Addressing this with separate issue and PR.

**Review by cloudxxx8 — APPROVED** [review]
LGTM after rebase

**Review by jpwhitemn — APPROVED** [review]
LGTM

**Pull request merged**
