### PR TITLE
Added methods in device profile client

### PR DESCRIPTION
**Pull request by jduranf**
Related to #324 

Signed-off-by: Joan Duran <jduran@circutor.com>

### CODE REVIEW

**Comment by jduranf** [comment]
@drasko fixed all http magic numbers and also infinite loops

**Comment by tonyespy** [comment]
@jduranf Your second commit also touches a lot more code than just the device profile client.  If you're going to do this type of cleanup across multiple services, it probably deserves its own PR.

**Comment by jduranf** [comment]
@tonyespy I just tried to fix the source of my errors, and all the changes are related to /core/clients, which I used in order to add methods in the device profile client.
But you are right, probably should be better to perform this kind of clean up in its own PR

**Comment by JPWKU** [comment]
recheck

**Comment by tonyespy** [comment]
Although the infinite loops might now be correct from a language standpoint, IMHOP there's no place for infinite loops in our services.  It looks to me like these loops are using when initializing a client used to talk to a dependent service.  At some point after a certain number of retries the service should give up and exit (after logging an error).

**Comment by tsconn23** [comment]
@tonyespy The loops you're referring to are how the service clients know whether a given endpoint has changed in Consul. They are only used when a service is passed the --consul flag. Their iteration pauses on this construct

```
select {
	case url := <-ch:
		d.url = url
}
```

whereby we wait to read a message out of the channel. Messages are published via this channel every 15 seconds (soon to be configurable) so this isn't a tight loop. When deploying in a multi-tenant scenario using Consul for service discovery, the endpoint of a service can change at any time so we use this to keep the client's endpoint up to date.

Also, note that this loop is happening in a go-routine so it's non-blocking for the execution flow. There will be other functionality that will use this pattern, like the service dependency resolution on bootstrap that you mention above. We can certainly have a loop like this check every second, for example, and then die after some period.

**Pull request merged**
