### PR TITLE
Schedule metadata

### PR DESCRIPTION
**Pull request by xmlviking**
Adding changes to Support Scheduler (many)

Changes:

Moved the scheduler database for “non-device” into its own new Mongo DB.
This new mongo DB is called “Scheduler”

Moved all of the router interaction logic to using the new “Scheduler” database.  Metadata is no longer used. 

Migrated all models to using the new public contract and private models’ structure.
* Created new Internal Mongo Models

Rebuilt the existing Router in Scheduler (uses Gorilla Mux now)
Migrated all of the router-based functions into “handlers”
Business logic now lives in go files which are germane to the types they interact with.
* Removed the old scheduler router logic and completely rebuilt.

Integrated Mockery, and Testify into Scheduler

Abstracted the scheduler CRUD operations and created a new SchedulerQueueClient.  This facilitates mocking and testing. 

TODO:
More Unit tests…will add them in the near future
Black Box Tests …will add them in the near future
Update some of the RAML entries for new parameters

Future: 
Migrate internal logic from making direct calls to scheduler or database and move to more of a domain event-based approach with handlers receiving channels publishes for asynchronous writing to scheduler and potentially some of the database activities

### CODE REVIEW

**Comment by xmlviking** [comment]
I will squash these down prior to final PR for entry :)

**Comment by xmlviking** [comment]
It looks like it's failing on a glide step downloading yaml2?  

[0m[91m[0;32m[INFO]	[m--> Fetching gopkg.in/yaml.v2
[0m[91m[0;33m[WARN]	[mUnable to checkout gopkg.in/yaml.v2
[0;31m[ERROR]	[mUpdate failed for gopkg.in/yaml.v2: Unable to get repository: Cloning into '/root/.glide/cache/src/https-gopkg.in-yaml.v2'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
: exit status 128
[0m[91m[0;31m[ERROR]	[mFailed to install: Unable to get repository: Cloning into '/root/.glide/cache/src/https-gopkg.in-yaml.v2'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
: exit status 128
[0m[91mmake: *** [Makefile:68: prepare] Error 1
[0mThe command '/bin/sh -c make prepare' returned a non-zero code: 2
make: *** [docker_config_seed] Error 2
Build step 'Execute shell' marked build as failure
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 9993 killed;
[ssh-agent] Stopped.

**Comment by xmlviking** [comment]
--recheck

**Comment by xmlviking** [comment]
-check

**Comment by xmlviking** [comment]
-recheck

**Comment by xmlviking** [comment]
--check

**Comment by xmlviking** [comment]
recheck

**Comment by tsconn23** [comment]
Just an update to anyone watching this PR, @xmlviking and I are going through a review process offline -- working issues as they arise in testing.

**Comment by xmlviking** [comment]
14:02:38 [0;31m[ERROR]	[mUpdate failed for github.com/hashicorp/consul: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-hashicorp-consul'...
14:02:38 error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
14:02:38 fatal: The remote end hung up unexpectedly
14:02:38 fatal: early EOF
14:02:38 fatal: index-pack failed
14:02:38 : exit status 128

Issues with downloading consul from the build.

**Comment by xmlviking** [comment]
-recheck

**Comment by xmlviking** [comment]
check

**Comment by xmlviking** [comment]
recheck

**Pull request merged**
