### PR TITLE
feat: Consume breaking authentication change to go-mod-core-contracts

### PR DESCRIPTION
**Pull request by bnevis-i**
This commit is an omnibus update of go.mod dependencies, including the breaking change to go-mod-core-contracts. This commit add support for sending outgoing JWTs from core services to device service REST APIs.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)  No new functionality added
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)  Only make test and smoke test via edgex-compose.
- [ ] I have opened a PR for the related docs change (if not, why?)  Change is not user facing

## Testing Instructions

`make test` in edgex-go

`make docker` in edgex-go and `make run dev` in edgex-compose

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@bnevis-i , you conflict to resolve.

**Comment by bnevis-i** [comment]
@lenny-intel Thanks.  Hopefully resolved now.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
