### PR TITLE
feat(core-data):To improve core-data fuzzing test coverage with swagger…

### PR DESCRIPTION
**Pull request by vli11**
… file update

Closes: #4689

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
run with restler fuzzing test tool:

make docker-fuzz
make fuzz-test-data

the coverage was 20/23 before, but with this PR change, and a manual fix on restler grammar, I'm able to get it to 23/23 coverage.

### CODE REVIEW

**Comment by jim-wang-intel** [comment]
## Testing Instructions
run it with restler fuzzing test tool

what is the expected output, can you add an example to check against it?

**Review by bnevis-i — APPROVED** [review]

**Comment by bnevis-i** [comment]
@vli11 Fuzzing is not a scope.  See https://github.com/edgexfoundry/edgex-go/blob/main/.github/semantic.yml#L15

**Comment by vli11** [comment]
> ## Testing Instructions
> 
> run it with restler fuzzing test tool
> 
> what is the expected output, can you add an example to check against it?

the coverage was 20/23 before, but with this PR change, and a manual fix on restler grammar, I'm able to get it to 23/23 coverage.

**Comment by vli11** [comment]
> @vli11 Fuzzing is not a scope. See https://github.com/edgexfoundry/edgex-go/blob/main/.github/semantic.yml#L15

amended the PR message.

**Review by bnevis-i — APPROVED** [review]

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Pull request merged**
