### PR TITLE
feat(data): Enhance the performance of events deletion

### LINKED ISSUE #3708: [Core Data] Delete events and readings by key-ids directly
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core data

### Is this a regression?

 No

### Description and Minimal Reproduction
When there are very much events and readings, the redis takes up a lot of memory space, maybe fulling the whole memory.
And then delete events and readings by age, these functions (getEventReadingIdsByKeyScoreRange/ asyncDeleteReadingsByIds / asyncDeleteEventsByIds) will get objects of events or readings by key-ids, which need more memory for these objects.

## 🔥 Exception or Error
<pre><code>

This case will make memory full and cpu spiking. What is much worse, the system may be crash.

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu Core, memory 4G
**EdgeX Version:**
2.0.1-dev.43

**Anything else relevant?**
First, get events and readings key-ids, don't get object, and delete events and readings by key-ids directly.

### PR DESCRIPTION
**Pull request by weichou1229**
Retrieve the eventId from storeKey instead of querying the eventObj to get the eventId.

Closes #3708 

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
  **unit tests not impacted**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  **docs not impacted**

## Testing Instructions

1. Run the core-data service and add events
2. Test `delete event by age` and `delete event by deviceName` API

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by lenny-intel — CHANGES_REQUESTED** [review]
@wangshihui , please complete the PR template. I.e. comment `why` on items not checked.
Can simply be `unit tests not impacted` and `docs not impacted`

**Comment by weichou1229** [comment]
Modified the PR description.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
