### PR TITLE
fix: Re-merge SECURITY.md

### LINKED ISSUE #2687: Merge SECURITY.md from Geneva to Master
# 🐞 Bug Report

### Affected Services

 The issue is located in: SECURITY.md

### Is this a regression?

 Yes, details of the EdgeX security related services and debugging tips captured during Geneva were lost in a merge.

### Description and Minimal Reproduction

`git diff d6a74791 aa472f58 SECURITY.md`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** edgex-go/master

**EdgeX Version:**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by andresrinivasan**
Signed-off-by: André Srinivasan <andre@redislabs.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Documentation was lost in a merge

Issue Number: 
Fixes #2687 

## What is the new behavior?

Documentation has been restored.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bnevis-i** [comment]
@hutchic Colin, this one was awaing your review. Never got added to the project board.

**Comment by ernestojeda** [comment]
recheck

**Review by bnevis-i — DISMISSED** [review]

**Comment by bnevis-i** [comment]
@andresrinivasan By updating the branch I torpedoed the semantic PR checker.  Please get me on slack, let's rebase and fix this, and I will approve right away.

**Comment by bnevis-i** [comment]
@andresrinivasan This commit needs to be updated to semantic PR standards (amend existing commit and change commit message), rebased, and force pushed.

**Comment by bnevis-i** [comment]
@andresrinivasan Ping.  This PR is unmergeable (see PR status panel for details)

**Comment by andresrinivasan** [comment]
Sorry. Will correct this week.

**Comment by bnevis-i** [comment]
@andresrinivasan Still failing semantic PR checker.  Please commit --amend and force push and make the commit title "fix: <description>"

**Comment by bnevis-i** [comment]
recheck

**Review by bnevis-i — APPROVED** [review]

**Pull request merged**
