### PR TITLE
#283 Remove Unused Schedule Property from domain/models/event.go

### PR DESCRIPTION
**Pull request by yanghua**
Signed-off-by: yanghua <yanghua1127@gmail.com>

cc @tsconn23

### CODE REVIEW

**Comment by tsconn23** [comment]
recheck

**Comment by chenchix** [comment]
recheck

**Comment by yanghua** [comment]
@tsconn23 @chenchix was it coursed by Jenkins? It built successfully in my local.

**Comment by tsconn23** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Pull request merged**
