### PR TITLE
fix(all): http response cannot be completed

### PR DESCRIPTION
**Pull request by wangshihui**
revcover panic when http status is zero.(may cased by tcp connection cannot be established)

http.go a tool for all core module.

Signed-off-by: shihui.wang <shihui.wang@thundersoft.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by wangshihui** [comment]
fix the pre pr issue
#3652 (comment)

**Comment by cloudxxx8** [comment]
by the way, we fixed the possibility to cause the status code being zero in the following PR:
https://github.com/edgexfoundry/go-mod-core-contracts/pull/646/files

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
Please open an issue to describe the problem before PR creation next time.  Thanks.

**Comment by wangshihui** [comment]
> by the way, we fixed the possibility to cause the status code being zero in the following PR:
> https://github.com/edgexfoundry/go-mod-core-contracts/pull/646/files
this is a better solution

> Please open an issue to describe the problem before PR creation next time. Thanks.
ok got it

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
Since there is a specific status code range, we should just use `if` statement to check `statusCode` instead of recover() func.
Also, I thought 500 internal server error is better than 503 service unavailable, because the error is unkown.

```
if statusCode < 100 || statusCode > 900 {
  w.WriteHeader(http.StatusInternalServerError)
}
```

**Comment by wangshihui** [comment]
> Since there is a specific status code range, we should just use `if` statement to check `statusCode` instead of recover() func.
> Also, I thought 500 internal server error is better than 503 service unavailable, because the error is unkown.
> 
> ```
> if statusCode < 100 || statusCode > 900 {
>   w.WriteHeader(http.StatusInternalServerError)
> }
> ```
ok  push new commit as above.

BTW
As this logic is from `http.checkWriteHeaderCode` a private func. so didnot pick  it at the first commit.  
and this PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/646/files  makes sure the statusCode  is a correct http status code. 
so this PR is only  as a guarantee  in case of unkonw use case.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
