### PR TITLE
Apply errorConcept pattern to core-command REST Handler

### LINKED ISSUE #1860: Apply error-handling pattern to core-command and core-data REST Handlers
# 🚀 Feature Request

### Relevant Package

- core-data
- core-command

### Description

In core-metadata, a pattern has been put in place in effort to create common way of handling HTTP errors. This approach uses a set of structs referred to as ErrorConcepts. These structs encapsulate all of the properties needed for type-checking, setting the error on the responseWriter, and logging the error. 

We need to apply this same pattern of error-handling to the core-data and core-command services.

### Describe the solution you'd like

The recommended solution is to go through core-data and core-command updating all error-handling to use the same pattern used in core-metadata REST handlers.

This effort may include abstracting out common errors in both core-command and core-data and reusing ErrorConcepts where applicable.

### Describe alternatives you've considered

None

### PR DESCRIPTION
**Pull request by brandonforster**
Fixes #1860.

This PR contains a large refactor for core command. This PR's functionality should be verified as well as ensuring there are no regressions from the previous code.

### CODE REVIEW

**Comment by michaelestrin** [comment]
Dependent on https://github.com/edgexfoundry/blackbox-testing/issues/276 to validate/verify proper functionality.

**Comment by michaelestrin** [comment]
@jbonafide623 -- please do a first-pass review on this PR.

**Comment by michaelestrin** [comment]
https://github.com/edgexfoundry/edgex-go/issues/1907

**Comment by brandonforster** [comment]
Closing, needs additional work done. Will reopen when ready.

**Pull request closed without merging**
