### PR TITLE
docs(data): Update docs to use object value in the Event tags

### LINKED ISSUE #3669: Remove unused variables in the infrastructure/redis package
# 🐞 Bug Report

### Affected Services

 The issue is located in: all

### Is this a regression?
No

### Description and Minimal Reproduction
Those two variables are unused.
https://github.com/edgexfoundry/edgex-go/blob/729eb4739df12e156b446759f30c8b9b764bc7ef/internal/pkg/infrastructure/redis/client.go#L22-L23

We use the counterparts:
https://github.com/edgexfoundry/edgex-go/blob/729eb4739df12e156b446759f30c8b9b764bc7ef/internal/pkg/db/redis/client.go#L29-L30

### PR DESCRIPTION
**Pull request by weichou1229**
Update event schema and example to use object value in the Event tags

Closes #3669

Signed-off-by: bruce <weichou1229@gmail.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **not impact to the unit test**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  **Only update swagger API**

## Testing Instructions

1. Modify the go.mod to replace the core-contracts lib
2. Run core-data 
3. Add event and query event to see the change

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cloudxxx8 , @jpwhitemn , do we need to change the swagger publishing to publish to 2.1.0 now so these changes don't overwrite what is the for 2.0.0?

**Comment by weichou1229** [comment]
Updated the core-data swagger API version from 2.0.1 to 2.1.0

**Comment by cloudxxx8** [comment]
> @lenny-intel I updated the core-data swagger API version from 2.0.1 to 2.1.0, then the swagger will publish new version API.

That's right.  Let's do it.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
