### PR TITLE
Add API v1 documents that support swagger

### LINKED ISSUE #2155: Document System Management APIv1 using Swagger
For Geneva, the project is moving towards individual working groups being responsible for providing documentation of their service's public APIs using Swagger.  This is a placeholder issue to capture this requirement.  Will amend when additional information is available on how this is to be coordinated/accomplished project-wide.

### PR DESCRIPTION
**Pull request by cherrycl**
Adding API v1 documents that support swagger.
Fix #2155 #2156 #2157 #2158 #2159 #2160 #2161

Signed-off-by: Cherry Wang <cherry@iotechsys.com>

### CODE REVIEW

**Comment by cherrycl** [comment]
> Have not reviewed content. Will do so once documents are relocated as requested below.
> 
> For historical purposes, documents should be placed in a directory that includes the entire semver -- i.e. major, minor, and patch release numbers. If these documents are representative of the RAML used for Fuji (which is what their internal version numbers indicate), they should be placed in api/openapi/v1.1.1.

@michaelestrin Changed the folder name from v1 to v1.1.1

**Comment by michaelestrin** [comment]
> Changed the folder name from v1 to v1.1.1

@cherrycl I made a related mistake and didn't update this issue.  In a separate PR, I versioned the v2 documents in the same way that I requested you to rename the v1 documents.  I had some subsequent discussion during yesterday's certification working group call that lead me to revert my change.  I didn't update this issue to reflect that and I apologize for creating additional work for you.

I will pull your branch, revert the v1 ->  v1.1.1 change, push it, and get a review going.

**Comment by michaelestrin** [comment]
@AnthonyMBonafide please review for completeness and to ensure it reflects the current state of the v1 API contracts.

**Comment by cloudxxx8** [comment]
@AnthonyMBonafide Those files are converted from the existing RAML files, so the content are the same as what we have right now.
May we merge this PR first to confirm the API file location and open issues to refine each one?
Or, we just leave V1 in RAML and use Swagger for V2 only.

**Comment by michaelestrin** [comment]
Accepted and merged per:

image

**Pull request merged**
