### PR TITLE
(fuji) Fixed bug with using Redis for core-command in Docker.

### LINKED ISSUE #2108: Config Seed not setting Support Command's DB for Redis
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
Command Service

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Edinburgh (Possibly), but based on the code it should have been in Edinburgh 

### Description and Minimal Reproduction

- Run  developer-scripts/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- After about 15 secs `edgex-core-command` will fail and stop
- Use Portainer (localhost:9000) to view logs for `edgex-core-command` which will show it can't find the DB.
- Use Consul to view Core Cammand's DB settings. http://localhost:8500/ui/dc1/kv/edgex/core/1.0/edgex-core-command/Databases/Primary
   - Host is `edgex-mongo` instead of `edgex-redis`
   - Type is `mongodb` instead of `redisdb`

## 🔥 Exception or Error
<pre><code>

Core Command fails to start with following error:
```
level=WARN ts=2019-11-11T20:19:02.1956017Z app=edgex-core-command source=database.go:125 msg="couldn't create database client: no reachable servers"
```
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Windows
**EdgeX Version:**
Fuji WIP

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by brandonforster**
Fixes #2108 in Fuji.

Signed-off-by: Brandon Forster <brandonforster@gmail.com>

Verification steps:

1. Create a local docker image for `config-seed`.
2. Build a container using that image.
3. Edit http://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml so that your local container is pulled instead of the remote Nexus image. This will be on line 70.
4. Allow the build to run and proceed.
5. Ensure core-command has not died.
6. After the containers are running, inspect Consul at http://localhost:8500/ui/
7. Navigate to the core-command configuration, and visually inspect that Redis is set as the default provider.

### CODE REVIEW

**Comment by anonymouse64** [comment]
@brandonforster what does step 4:

> Allow the build to run and proceed.

entail? just running docker-compose up? is there something else I have to build ?

**Comment by brandonforster** [comment]
> @brandonforster what does step 4:
> 
> > Allow the build to run and proceed.
> 
> entail? just running docker-compose up? is there something else I have to build ?

@anonymouse64 I'm referencing the 
> After about 15 secs `edgex-core-command` will fail and stop

language in the original issue. You shouldn't need to have external tools running.

**Comment by brandonforster** [comment]
rebased

**Comment by brandonforster** [comment]
recheck

**Comment by brandonforster** [comment]
recheck

**Comment by brandonforster** [comment]
recheck

**Comment by anonymouse64** [comment]
I trust the other reviewers who approved this verified the fix before approving, thus removing my request for review

**Pull request merged**
