### PR TITLE
Tech-debt: removing "legacy" sub-command

### PR DESCRIPTION
**Pull request by jim-wang-intel**
Removing the legacy sub-command from security-secrets-setup because it is no longer used.

 Fixes: #2570

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

In the micro-service, security-secrets-setup, there is "legacy" sub-command no longer being used.  It is desirable to remove this to reduce the code size hence the maintenance efforts.
Issue Number: #2570 

## What is the new behavior?
No legacy subcommand is being used anywhere in the code today, and "legacy" sub command should no longer be available.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jim-wang-intel** [comment]
cc: @eno-intel @walt-intel

**Comment by lenny-intel** [comment]
@jim-wang-intel,  Per our point release plan, please don't merge this PR until after release is tagged. THX!

**Comment by lenny-intel** [comment]
@tingyuz , we are suppose to hold off on merging the outstanding PRs unless that are to be included in the point release....

**Comment by tingyuz** [comment]
@lenny-intel yes sorry I just realized that we are in the grace period..:( Let me check with Jim to see what we can do.

**Pull request merged**
