### PR TITLE
feat(V2): Add correlation id into log

### PR DESCRIPTION
**Pull request by cloudxxx8**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2747

## What is the new behavior?
Add correlation id when writing error or debug logs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by lenny-intel — COMMENTED** [review]
In V1 there is a TRACE log of correlation ID for add API's not just when there is an error.
https://github.com/edgexfoundry/edgex-go/blob/79dcaa9942ed3f8be87c186347b0da1d7714bd40/internal/pkg/correlation/middleware.go
We should have something similar in V2.

**Review by lenny-intel — APPROVED** [review]
LGTM, my other comment needs to be addressed in separate PR.

**Comment by cloudxxx8** [comment]
> In V1 there is a TRACE log of correlation ID for add API's not just when there is an error.
> https://github.com/edgexfoundry/edgex-go/blob/79dcaa9942ed3f8be87c186347b0da1d7714bd40/internal/pkg/correlation/middleware.go
> We should have something similar in V2.

@lenny-intel , we have already reused middleware.go in V2
https://github.com/edgexfoundry/edgex-go/blob/4c1a6d2ffbdc3154b41bea1622b22c22abf998aa/internal/core/data/v2/router.go#L31-L33

**Comment by cloudxxx8** [comment]
rebased from master

**Review by weichou1229 — APPROVED** [review]
LGTM

**Review by judehung — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
> we have already reused middleware.go in V2

Excellent! THX!

**Pull request merged**
