### PR TITLE
Output coverage report to file during "make test"

### PR DESCRIPTION
**Pull request by MightyNerdEric**
This relates to this ci-management change: https://github.com/edgexfoundry/ci-management/pull/373

### CODE REVIEW

**Comment by MightyNerdEric** [comment]
recheck

Failure does not appear related to my change. Looks like a connection failure.

**Comment by MightyNerdEric** [comment]
recheck

**Comment by MightyNerdEric** [comment]
Changed the filename to coverage.out, and added coverage.out to the .gitignore.

**Comment by tsconn23** [comment]
recheck

**Pull request merged**
