### PR TITLE
build: Update to latest go-mods

### PR DESCRIPTION
**Pull request by lenny-intel**
**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) ) **existing unit tests suffice**
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?) **unit tests suffice**
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
run `make test`

### CODE REVIEW

**Review by bnevis-i — APPROVED** [review]

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by bnevis-i** [comment]
@lenny-intel Don't ever think I've seen go segfault before.  I'll run this in an arm VM and report back.

**Comment by bnevis-i** [comment]
> @lenny-intel Don't ever think I've seen go segfault before. I'll run this in an arm VM and report back.

@lenny-intel I ran this in QEMU with a cortex-a72 processor emulation and did not get a segfault.  Don't have a clue why this is failing.

**Comment by bnevis-i** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
closing PR to recreate to see if ARM64 build issue is resolved

**Pull request closed without merging**
