### PR TITLE
fix(command): Using the Device Service response code for Get Command

### PR DESCRIPTION
**Pull request by weichou1229**
Signed-off-by: bruce <weichou1229@gmail.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

- Run core service and device service
- Test with debug mode to inspect the response code

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@weichou1229, @cloudxxx8, Please follow PR template completely, i.e. state why on items not checked. Can simply be `no applicable for this change` or `doesn't impact docs`

**Comment by lenny-intel** [comment]
@weichou1229, @cloudxxx8, Also, this has a related issue (https://github.com/edgexfoundry/edgex-go/issues/3668)? That should be referenced in the commit message which would have auto populated in the description.

**Comment by weichou1229** [comment]
Got it. Modified the PR description.

**Comment by lenny-intel** [comment]
> Got it. Modified the PR description.

Thanks! :-)

**Pull request merged**
