### PR TITLE
Provide mongo credentials in all configuration.toml files

### PR DESCRIPTION
**Pull request by difince**
Mongo is going to be started with enabled access control.(see [here](https://github.com/edgexfoundry/docker-edgex-mongo/issues/77))
This means that each service that connects to mongo will need to authenticate itself even when
EDGEX_SECURITY_SECRET_STORE = false, or the service is run by snap.

Signed-off-by: difince <dianaa@vmware.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/edgexfoundry/edgex-go/issues/2380
## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

### CODE REVIEW

**Comment by michaelestrin** [comment]
Added security-related reviewers.  Larger question -- should we be propagating "standard" persistence credentials into individual service configuration files?

**Comment by jim-wang-intel** [comment]
> 
> 
> Added security-related reviewers. Larger question -- should we be propagating "standard" persistence credentials into individual service configuration files?

This is a good question to discuss:  I thought the current Mongo's credentials for services are generated on the fly and uploaded to Vault via Vault worker.  Is this credentials from toml file mongo's ROOT username and password? If so, it looks insecure via this approach...

**Comment by difince** [comment]
@jim-wang-intel No, these are not  mongo's ROOT username and password.
You are correct, Mongo credentials are generated on the fly and uploaded into Vault via vault-worker but only when the security is enabled (i.e when EDGEX_SECURITY_SECRET_STORE=True )
If the security is disabled, microservices should nevertheless authenticate itself in front of mongo. This authentication will become mandatory when mongo access control is enabled

**Comment by difince** [comment]
> should we be propagating "standard" persistence credentials into individual service configuration files

Is you question equal to: 

- "Is the configuration file the right place for storing these "standard" credentials ? "

accepting that "Standard Credential" = The credentials used when security is disabled

**Pull request merged**
