### PR TITLE
build: Add convenient alias for each services build and docker target

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **N/A**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?) 
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
run make with each of the alias targets
Verify the proper target is executed.

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Review by ernestojeda — APPROVED** [review]
Nice aliases

**Comment by lenny-intel** [comment]
@farshidtz , snap test is failing on this PR that simply added addition make targets. It is also failing on this PR: https://github.com/edgexfoundry/edgex-go/pull/4119

**Comment by farshidtz** [comment]
> @farshidtz , snap test is failing on this PR that simply added addition make targets.

Github sometimes becomes too slow and the operations happen at a different order than originally expected. Will improve this. Moreover, rarely get strange errors like `Web server failed: listen tcp 127.0.0.1:59880: bind: address already in use` or  other ports on the first run. This now passed after a few retries. 

> It is also failing on this PR: #4119

This was an actual implementation issue: https://github.com/edgexfoundry/edgex-go/pull/4119#discussion_r944276385

**Pull request merged**
