### PR TITLE
many: rename ReadMaxLimit to MaxResponseObjectLength, set default to 50k

### PR DESCRIPTION
**Pull request by anonymouse64**
This patch fixes part of what is discussed in issue #1326, namely that the name of the configuration item isn't clear and that the default is too low.

Now, the config item's name more accurately reflects what it is limiting, and
setting it higher helps with deploying results, where you can easily get
more than 100 items in a few seconds with the example device services.

I set the default here to 50000, but can easily change it if folks think that's too high, but as I mentioned on the issue.

### CODE REVIEW

**Comment by tsconn23** [comment]
I personally don't know about the name `MaxResponseObjectLength`. It's not clear to me what that means. If I were someone without much history on this, it could mean the maximum size of a single object in the response...or it could mean the maximum size in bytes of the response. I would propose something like `MaxResultCount`. @jduranf @mhall119 Do you have an opinion?

**Comment by anonymouse64** [comment]
How about `MaxResponseObjectsCount`? Then `Objects` is plural implying multiple objects in a response, and Count also suggests this

**Comment by tobiasmo1** [comment]
My 2 cents. I agree using length in the name implies it limits byte size of object or overall response itself, and MaxResponseObjectsCount is an improvement. I wish it was simpler name like MaxResponseCount.

Are **all** responses to requests that involve database queries governed by this limit (across REST calls to any/all core services)?

**Comment by anonymouse64** [comment]
I agree with @tobiasmo1 that it would be nice to have it shorter, but the issue I see with `MaxResponseCount` is that it doesn't make it clear that the thing we're limiting is the number of things _in a response_, not the number of _responses_.

**Comment by tsconn23** [comment]
> the thing we're limiting is the number of things _in a response_

Results, right? `MaxResultCount`

**Comment by tobiasmo1** [comment]
It does seem `MaxResultCount` is best so far. It characterizes the # limit top level core-contract data model objects returned in response to GET query. MaxRowCount would be too db centric.

**Comment by anonymouse64** [comment]
Yeah I think `MaxResultCount` is better. I'll update the PR with that

**Comment by tsconn23** [comment]
recheck

**Pull request merged**
