### PR TITLE
Refactor SMA InvokeOperation implementation

### PR DESCRIPTION
**Pull request by anonymouse64**
This resolves the following issues:
* #771 
* #770 
* #769 
* #768 
* #767 
* #751 

Note that this PR replaces #750

### CODE REVIEW

**Comment by anonymouse64** [comment]
As per conversation with @jpwhitemn leaving this open for now, but for immediate Delhi release we will be instead using #750 
This PR may or may not be taken up for Delhi dot release.

**Comment by anonymouse64** [comment]
@akramtexas @jpwhitemn I implemented the "custom" operation type that was discussed in the meeting here as well so that y'all can see what we were talking about specifically.

**Comment by akramtexas** [comment]
> @akramtexas @jpwhitemn I implemented the "custom" operation type that was discussed in the meeting here as well so that y'all can see what we were talking about specifically.

Thanks @anonymouse64 I will take a look 👍

**Comment by anonymouse64** [comment]
@akramtexas any word on accepting this change for Edinburgh?

**Comment by brandonforster** [comment]
[If you'd like to merge into master instead, you're going to run into conflicts with this PR I just committed](https://github.com/edgexfoundry/edgex-go/pull/887)

**Comment by akramtexas** [comment]
> @akramtexas any word on accepting this change for Edinburgh?
@anonymouse64 I need to circle back with you on Monday, as I'm OOO tomorrow (Friday). I'll be in touch, thanks!

**Comment by akramtexas** [comment]
> > @akramtexas any word on accepting this change for Edinburgh?
> > @anonymouse64 I need to circle back with you on Monday, as I'm OOO tomorrow (Friday). I'll be in touch, thanks!

- Examination of this PR is ongoing... Thanks for your patience

**Comment by jpwhitemn** [comment]
Closing this PR for now as @akramtexas is working the new interfaces and implementation incorporating much of this design.

**Pull request closed without merging**
