### PR TITLE
Update Dependency Versions (go-mod-bootstrap, go-mod-core-contracts)

### PR DESCRIPTION
**Pull request by michaelestrin**
Also removes missed usages of export service-related constants
that were removed in the latest version of go-mod-core-contracts.

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2245
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2234

Signed-off-by: Michael Estrin <m.estrin@dell.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
@AnthonyMBonafide and @brandonforster added as reviewers; merge does not require review/approval from both.

**Comment by MightyNerdEric** [comment]
recheck

**Comment by MightyNerdEric** [comment]
recheck

**Comment by MightyNerdEric** [comment]
recheck

**Comment by MightyNerdEric** [comment]
recheck

**Comment by MightyNerdEric** [comment]
recheck

**Comment by michaelestrin** [comment]
recheck

**Pull request merged**
