### PR TITLE
fix: Set exitcode of secrets-config for command execution errors

### LINKED ISSUE #4337: Zero exit code on secrets-config errors
# 🐞 Bug Report
The `secrets-config` command does not consistently exit with the right code. In some error cases, it exits with zero code which complicates the usage by other programs.

### Affected Services [**REQUIRED**]
`secrets-config` CLI app

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
Setup:
```bash
$ snap install edgexfoundry --edge
edgexfoundry (edge) 3.0.0-dev.39 from Canonical✓ installed

$ openssl ecparam -genkey -name prime256v1 -noout -out private.pem && openssl ec -in private.pem -pubout -out public.pem
read EC key
writing EC key

$ KONG_ADMIN_JWT=`sudo cat /var/snap/edgexfoundry/current/secrets/security-proxy-setup/kong-admin-jwt`
```

:heavy_check_mark: Bad algorithm:
```bash
$ edgexfoundry.secrets-config proxy adduser --token-type jwt --user example --algorithm BAD --public_key public.pem --id 1000 --jwt $KONG_ADMIN_JWT
level=ERROR ts=2023-02-08T16:10:46.050346727Z app=secrets-config source=bootstraphandler.go:70 msg="/snap/edgexfoundry/4259/bin/secrets-config proxy adduser: argument --algorithm must be either 'RS256' or 'ES256'"
$ echo $?
2
```

:heavy_check_mark: Missing username:
```bash
$ edgexfoundry.secrets-config proxy adduser --token-type jwt --algorithm ES256 --public_key public.pem --id 1000 --jwt $KONG_ADMIN_JWT
level=ERROR ts=2023-02-08T16:11:02.878690792Z app=secrets-config source=bootstraphandler.go:70 msg="/snap/edgexfoundry/4259/bin/secrets-config proxy adduser: argument --user is required"
$ echo $?
2
```

:x: Bad file input (public key):
```bash
$ edgexfoundry.secrets-config proxy adduser --token-type jwt --user example --algorithm ES256 --public_key bad.pem --id 1000 --jwt $KONG_ADMIN_JWT
level=ERROR ts=2023-02-08T16:10:13.485267104Z app=secrets-config source=bootstraphandler.go:77 msg="failed to read public key from file bad.pem: open bad.pem: no such file or directory"
$ echo $?
0
```

:x: Bad JWT token (Kong Admin token):
```bash
$ edgexfoundry.secrets-config proxy adduser --token-type jwt --user example --algorithm ES256 --public_key public.pem --id 1000 --jwt badtoken
level=ERROR ts=2023-02-08T16:24:58.209231341Z app=secrets-config source=command.go:168 msg="{\"message\":\"Bad token; invalid JSON\"}"
level=ERROR ts=2023-02-08T16:24:58.209262189Z app=secrets-config source=bootstraphandler.go:77 msg="Create consumer request failed with code: 401"
$ echo $?
0
```

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:** 3.0.0-dev.39

**Anything else relevant?**

As a workaround, the program using `secrets-config` could look for "ERROR" in the standard output instead of checking the exit code.

### PR DESCRIPTION
**Pull request by bnevis-i**
Closes #4337

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
See use cases in #4337 for sample test cases to try to verify issue is fixed.

### CODE REVIEW

**Comment by bnevis-i** [comment]
@farshidtz  Please review this one-line fix.

**Review by farshidtz — APPROVED** [review]
I can't reproduce any of the previous errors because that functionality no longer exists. 
I did do some sanity checks and the error codes seem correct.

**Comment by farshidtz** [comment]
I don't think if this is a bug or feature. I noticed that the `-jwtTTL` takes both integer and go duration but not sure they both get accepted or if one is ignored.
```
$ sudo edgexfoundry.secrets-config proxy adduser --user example -useRootToken -jwtTTL 4
{"username":"example","password":"TYMMvc80BGdqYOu55VPIru8z4Ibr/ryytopuzd5nAQ2X"}

$ sudo edgexfoundry.secrets-config proxy adduser --user example -useRootToken -jwtTTL 4h
{"username":"example","password":"Kx2mBBwYRXo9HOC7SUUPrlrYoQowexC/S5k7rie32cNG"}
```
Given the description below, I expect only Go duration to be supported. Go's [time.Duration](https://pkg.go.dev/time#ParseDuration) rejects integer input: https://go.dev/play/p/E9nNy8Sw7pi
```
  -jwtTTL string
    	JWT created by vault identity provider lasts this long (default "1h")
```

**Comment by bnevis-i** [comment]
> I don't know if this is a bug or feature. I noticed that the `-jwtTTL` takes both integer and go duration but not sure they both get accepted or if one is ignored.
> 
> ```
> $ sudo edgexfoundry.secrets-config proxy adduser --user example -useRootToken -jwtTTL 4
> {"username":"example","password":"TYMMvc80BGdqYOu55VPIru8z4Ibr/ryytopuzd5nAQ2X"}
> 
> $ sudo edgexfoundry.secrets-config proxy adduser --user example -useRootToken -jwtTTL 4h
> {"username":"example","password":"Kx2mBBwYRXo9HOC7SUUPrlrYoQowexC/S5k7rie32cNG"}
> ```
> 
> Given the description below, I expect only Go duration to be supported. Go's [time.Duration](https://pkg.go.dev/time#ParseDuration) rejects integer input: https://go.dev/play/p/E9nNy8Sw7pi
> 
> ```
>   -jwtTTL string
>     	JWT created by vault identity provider lasts this long (default "1h")
> ```

proxy tls  --incert --inkey would fail in the same way if pointed to nonexistent files.

**Comment by bnevis-i** [comment]
@farshidtz 

Turns out I pass it directly to vault.  <https://developer.hashicorp.com/vault/docs/concepts/duration-format>

`--jwtTTL 5` turns out to be 5 SECONDS!

Will update command line help.

**Pull request merged**
