### PR TITLE
Removed Objects from DevicProfile and renamed DeviceObject to DeviceResource

### LINKED ISSUE #1007: Remove deprecated DeviceProfile.Objects field
Per our discussion with @trcox about device profiles, the [`DeviceProfile.Objects`](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/deviceprofile.go#L35) field should be removed as it was deprecated a long time ago.

We should also consider re-naming the [DeviceObject](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/deviceobject.go) struct to `DeviceResource`.

### PR DESCRIPTION
**Pull request by jduranf**
Fix #1007 

Just as a comment, the deviceprofile and their examples in core-metadata.raml are wrong. I just fixed the part related with this PR.

After this PR have been merged, device-sdk-go should be updated.

Signed-off-by: Joan Duran <jduran@circutor.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
@jduranf I'm going to temporarily put a hold on this while we sequence it with some other efforts related to the edgex-go contract integration with device services. More clarity early next week.

**Comment by tsconn23** [comment]
@jduranf Per discussion on the source issue I think we're ready for this to come in now.

https://github.com/edgexfoundry/edgex-go/issues/1007#issuecomment-458192442

Please rebase and address the conflict so we can get it reviewed.

**Comment by jduranf** [comment]
@tsconn23 done!

**Comment by tsconn23** [comment]
@jduranf LGTM pending requested changes to https://github.com/edgexfoundry/blackbox-testing/pull/145. Please rebase when you can. Thanks.

**Comment by tsconn23** [comment]
Created issue #1069 to address @tobiasmo1's comment above

**Pull request merged**
