### PR TITLE
Remove old java device-mqtt setup docs

### LINKED ISSUE #1055: Update Device MQTT setup docs to use Go version
The docs on https://docs.edgexfoundry.org/Ch-ExamplesMQTTDeviceService.html still refer to the old Java version of device-mqtt, they need to be updated to use the new Go version

### PR DESCRIPTION
**Pull request by weichou1229**
Fix #1055

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@mhall119 please help review this PR, thanks

**Comment by mhall119** [comment]
Is there anything from this old document that needs to be added to https://docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html or does that new doc contain all the needed info for running the MQTT device service?

**Comment by mhall119** [comment]
I see the comment on the issue about the content being duplicated

**Comment by brandonforster** [comment]
Please rebase.

**Pull request merged**
