### PR TITLE
fix(docs): Add examples to core-metadata v2 APIs

### LINKED ISSUE #2702: Add Core Metadata v2 API Response Examples
# 📚 Docs or Wiki Bug Report

### Description

 Example data shows data type currently, needs to update it to a valid value.

### What's the affected URL?**
 
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [ ] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:
closes #2702
## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
please help change the Patch method of DeviceProfile to Put

**Comment by cherrycl** [comment]
> please help change the Patch method of DeviceProfile to Put

Updated.

**Comment by cherrycl** [comment]
Add 400 status to get APIs.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
