### PR TITLE
refactor: Update for new service key names and overrides for hyphen to underscore

### PR DESCRIPTION
**Pull request by lenny-intel**
**Dependent on edgexfoundry/go-mod-core-contracts#613
Dependent on edgexfoundry/go-mod-bootstrap#216**

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?
Service key constants have the edgex- prefix

## What is the new behavior?
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE: Service key names used in configuration have changed.

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Review by cloudxxx8 — COMMENTED** [review]
The prefix in SECURITY.md should be modfied.
Please also modify the config API example in system-agent.yaml, core-data.yaml, and core-metadata.yaml under /openapi/v2/ folder.

**Comment by lenny-intel** [comment]
> The prefix in SECURITY.md should be modfied.
> Please also modify the config API example in system-agent.yaml, core-data.yaml, and core-metadata.yaml under /openapi/v2/ folder.

@cloudxxx8 , I addressed the YAML files. Remember that the container and host names will still start with `edgex-` prefix
The `SECURITY.md` is way outdated and needs many more changes than the scope of this PR. I have created a new issue to address updating it:
https://github.com/edgexfoundry/edgex-go/issues/3476

**Review by jim-wang-intel — CHANGES_REQUESTED** [review]
Could you also address the naming in snap too?

- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L189 
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L202 
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L204
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L221
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L251
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L269
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L284
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L299
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L314
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L330
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L367
- https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L369

then the naming will look much more consistent with the one from docker, too.

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Pull request merged**
