### PR TITLE
Fix three minor issues (with SMA docker container).

### PR DESCRIPTION
**Pull request by akramtexas**
Fix [#1371](https://github.com/edgexfoundry/edgex-go/issues/1371)

- Fix three minor issues (with SMA docker container).

### CODE REVIEW

**Comment by akramtexas** [comment]
- Requesting a review each from @anonymouse64 and @JPWKU 👍 
- I've added @tsconn23 and @jpwhitemn for visibility (since we are near the code-freeze point).

**Comment by akramtexas** [comment]
@anonymouse64 Would you like to test locally before I merge the PR? 👍

**Comment by anonymouse64** [comment]
@akramtexas Assuming someone else such as @tsconn23 has tested locally to make sure the container still works it's fine to pull this in, but someone should test it locally

**Comment by akramtexas** [comment]
> @akramtexas Assuming someone else such as @tsconn23 has tested locally to make sure the container still works it's fine to pull this in, but someone should test it locally

@anonymouse64 Perfect, totally agreed 👍 I had of course tested it locally as well (tested all operations on the SMA container).

**Comment by akramtexas** [comment]
Thank you all for the quick turnaround!

**Comment by tsconn23** [comment]
> @akramtexas Assuming someone else such as @tsconn23 has tested locally to make sure the container still works it's fine to pull this in, but someone should test it locally

Tested locally via `docker run --network="docker_edgex-network" -p 127.0.0.1:48090:48090/tcp edgexfoundry/sys-mgmt-agent-go:1.0.0-dev` after bringing everything else up via docker-compose.

**Comment by akramtexas** [comment]
And I tested locally after bringing up all containers (including the `SMA` container) via this snippet in my `docker-compose.yml`:
```
  system:
    image: edgexfoundry/sys-mgmt-agent-go:1.0.0-dev
    ports:
      - "48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logging
```

**Comment by akramtexas** [comment]
I find Postman to be a very convenient tool for issuing REST calls, and observing responses, etc., as in this screenshot of my integration tests for the `SMA`:
postman

**Pull request merged**
