### PR TITLE
Added SMA Agent Unit Tests

### PR DESCRIPTION
**Pull request by michaelestrin**
Additional refactoring to support unit tests.  Added unit tests (direct service implementation still needs tests).  Eliminated init.go's global variables.  Separated implementation into separate cohesive subpackages. Implemented Metrics and CommandExecutor abstractions.

https://github.com/edgexfoundry/edgex-go/issues/1486
Signed-off-by: Michael Estrin <m.estrin@dell.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
@anonymouse64 Going forward I'll try to keep commit size down.  I did have a series of commits that were subsequently squashed (and lost) for this PR.  I beg your indulgence to work with me on this particular review -- it's mostly code being moved around into new packages.  I'm not keen on the idea of reimplementing this work to recreate the various commits that existing before I squashed them into one.

**Comment by brandonforster** [comment]
@michaelestrin You could always surf the `reflog` if you're feeling brave.

I don't know that you should, though.

**Comment by michaelestrin** [comment]
Rebased.

**Comment by michaelestrin** [comment]
Rebased.

**Comment by michaelestrin** [comment]
Rebased.

**Comment by anonymouse64** [comment]
don't wait for me to review this I don't have the time unfortunately

**Pull request merged**
