### PR TITLE
doc: Save to docker-compose.yml

### PR DESCRIPTION
**Pull request by rzr**
Observed issue was:

```
docker-compose --version
docker-compose version 1.21.0, build unknown

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

Change-Id: Ia750efa6da96509e2e095ae8f76f094b2b01bde6
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by bnevis-i** [comment]
This PR is very much out-of-date and now one release behind. (Should refer to fuji not edinburgh.)

**Comment by rzr** [comment]
Here is the PR for fuji:
https://github.com/edgexfoundry/edgex-go/pull/2261

Once merged I will update this branch to handle nightly-build files

**Comment by bnevis-i** [comment]
@michaelestrin  This PR is waiting on your approval (merging blocked due to prior changes requested)

**Comment by michaelestrin** [comment]
@bnevis-i dismissed my prior review.

**Pull request merged**
