### PR TITLE
feat!: Remove --useradd and --userdel support from proxy-setup

### PR DESCRIPTION
**Pull request by bnevis-i**
This functionality has been relocated to secrets-config

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by lenny-intel** [comment]
@bnevis-i , there are TAF scripts that are dependent on this which need to be change to use the new utility before this PR is merged.

**Comment by cloudxxx8** [comment]
@jinlinGuan @cherrycl for awareness

**Comment by lenny-intel** [comment]
@bnevis-i , Need issue number.

**Comment by lenny-intel** [comment]
This PR is dependent on these issues being completed first:
https://github.com/edgexfoundry/developer-scripts/issues/361
https://github.com/edgexfoundry/edgex-taf/issues/247

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
