### PR TITLE
Use string instead of interface{} in Attributes

### LINKED ISSUE #1289: Replace Attributes data type with map[string]string in DeviceResource
To meet https://github.com/edgexfoundry/go-mod-core-contracts/issues/78

To make the data type of Attributes of DeviceResource simple, replace map[string]interface{} with map[string]string. interface{} was my suggestion to make the Device Service more complex. In addition, map[string]string meets the C SDK design.

I have prepared a branch for updating models in db package
Waiting for PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/79 reviewed and merged

### PR DESCRIPTION
**Pull request by cloudxxx8**
Replace Attributes data type with map[string]string in DeviceResource
fix #1289

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
@cloudxxx8 Rebase when you have a chance and we can pull this in.

**Comment by cloudxxx8** [comment]
@tsconn23 rebased, thanks

**Comment by andresrinivasan** [comment]
@cloudxxx8 Doesn't this need to be propagated to the Redis impl?

**Comment by cloudxxx8** [comment]
@andresrinivasan, redis implementation is using the model in go-contract, so it doesn't need to update here
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/device_profile.go#L32

**Comment by andresrinivasan** [comment]
Ah, got it. Thanks.

**Pull request merged**
