### PR TITLE
feat: Add go-winio to attribution (new SPIFFE dependency)

### PR DESCRIPTION
**Pull request by bnevis-i**
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

This PR is necessary to make https://github.com/edgexfoundry/edgex-go/pull/4000 mergeable.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## New Dependency Instructions (If applicable)
New dependency is being introduced by go-spiffe, which is approved.

### CODE REVIEW

**Comment by jim-wang-intel** [comment]
new from version 2.1?

**Comment by bnevis-i** [comment]
> new from version 2.1?

Yes.  Can't apply dependabot update without it.

**Review by jim-wang-intel — DISMISSED** [review]

**Comment by bnevis-i** [comment]
recheck

**Comment by farshidtz** [comment]
The snap build issue has been resolved by #4035. Please ignore the failed check.

**Pull request merged**
