### PR TITLE
Update OAS API version to 1.2.1

### LINKED ISSUE #2561: Need to change version to 1.3.0 for oas api docs
# 📚 Docs or Wiki Bug Report

### Relevant Package

 This issue is for updating API documents.

### Description
 A clear and concise description of the problem or missing capability...
Since the geneva is released, we would like to set 1.2.0 OAS API docs to public on swaggerHub, need to change to version to 1.3.0 to avoid overriding.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [ ] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:
Fix #2561 
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
@AnthonyMBonafide There are some new improvement you made in Geneva, and we want to publish them, for example
https://github.com/edgexfoundry/edgex-go/pull/2533
https://github.com/edgexfoundry/edgex-go/pull/2541

Could you please merge this PR?  Then, we can publish v1.2 API documents onto SwaggerHub, or it will always be override by Jenkins to private.
Thanks.

**Comment by AnthonyMBonafide** [comment]
Would it be better to update the version of the documents from `1.2.0` to `1.2.1` rather than `1.3` to avoid a version override? My thought is that it would be better if the versions of EdgeX and the public Swagger documentation are more inline so that users can easily identify the correct version. For Geneva we are calling it version `1.2`, to keep the minor versions in sync we can simply increase the patch version. This would signal to users that the contents are still valid for version `1.2`, but only contain minor corrections. Looking at this from the point of view of a "power user" of the system, if I wanted to look at the Swagger documentation for the `Geneva` release which is `1.2`, I would naturally look for that matching version in the Swagger docs and look for the latest `1.2.x` version of the documentation.

**Comment by cloudxxx8** [comment]
actually, this is my original intention to set up the Jenkins pipeline to automatically update the Swagger files.  @ernestojeda @jamesrgregg May we set the Swagger file upload as public?  I can't see any advantage to keep uploading Swagger file as private.  If you feel fine, we can create the PR to modify it.
@cherrycl please help rebase this PR and modify the version to 1.2.1
thanks for the feedback, @AnthonyMBonafide

**Comment by cherrycl** [comment]
Changed version to 1.2.1.

**Pull request merged**
