### PR TITLE
Fix issue 465: “/event/scrub” block long time

### PR DESCRIPTION
**Pull request by unanao**
Signed-off-by: Sun Jianjiao <sunjj@mingdutech.com>

### CODE REVIEW

**Comment by jduranf** [comment]
recheck

**Comment by jduranf** [comment]
recheck

**Comment by unanao** [comment]
> Please rebase and commit again. MongoDB location have been changed and InfluxDB have been removed.

@jduranf The PR‘s target branch is california,  california branch still has influxdb.

**Comment by jduranf** [comment]
@unanao you are right, I didn't notice the target was california... anyway, delhi will be released in a couple of weeks, why not close this PR and create a new PR targeting master branch? This PR should be done anyway

Also, if you still want to target california branch, there are a couple of checks which fails and should be solved. And you modified several snap files, which shouldn't be modified in this PR.

**Comment by unanao** [comment]
> @unanao you are right, I didn't notice the target was california... anyway, delhi will be released in a couple of weeks, why not close this PR and create a new PR targeting master branch? This PR should be done anyway
> 
> Also, if you still want to target california branch, there are a couple of checks which fails and should be solved. And you modified several snap files, which shouldn't be modified in this PR.

@jduranf  I create a new pull request for master.

**Pull request closed without merging**
