### PR TITLE
build: remove VERSION file as git-semver now manages version

### PR DESCRIPTION
**Pull request by ernestojeda**
TBD...Need to discuss in TSC meeting.

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by anonymouse64** [comment]
What is the plan to make snap builds work without the VERSION file? 

```
12:19:23 Pulling version 
12:19:23 cat: VERSION: No such file or directory
12:19:24 Failed to run 'override-pull': Exit code was 1.
12:19:34 Build step 'Execute shell' marked build as failure
```

**Comment by ernestojeda** [comment]
> What is the plan to make snap builds work without the VERSION file?
> 
> ```
> 12:19:23 Pulling version 
> 12:19:23 cat: VERSION: No such file or directory
> 12:19:24 Failed to run 'override-pull': Exit code was 1.
> 12:19:34 Build step 'Execute shell' marked build as failure
> ```

Couple things...
- We should be able to safely remove the `edgex-go-snap-master-verify` and `edgex-go-snap-master-verify-arm` JJB managed jobs. We have an inline Snap stage that can be added to the pipeline job (currently commented out). It's a couple of lines of code and because git-semver is used in the pipeline the VERSION file is automatically written to the workspace. In all honesty I thought we had removed the verify snap jobs.
- The [nightly snap job](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/job/edgex-go-daily-snap/) is being updated to use the VERSION file created by git-semver

**Comment by anonymouse64** [comment]
@ernestojeda great thanks for specifying, one more question what is the plan for local builds of the snap? Since the builds will be local there will be no VERSION file and thus it will fail to build unless the developer creates a VERSION file.

**Comment by ernestojeda** [comment]
> @ernestojeda great thanks for specifying, one more question what is the plan for local builds of the snap? Since the builds will be local there will be no VERSION file and thus it will fail to build unless the developer creates a VERSION file.

I wrote a note about this in the snapcraft.yaml file [here](https://github.com/edgexfoundry/edgex-go/pull/2645/files#diff-5fde7a6d86053f0e1d88c0a2a238941fR418-R419). I added the VERSION file to the .gitignore so if one cares about local snap development they could write a local VERSION file to allow the snap to build. There is a similar concept in the `make version` target will look for the version in the VERSION file and if it cannot find a file it returns `0.0.0`. So another option might be to update snapcraft.yaml to use `make version` rather than `cat VERSION`. Not sure if that is possible.

**Comment by anonymouse64** [comment]
> So another option might be to update snapcraft.yaml to use make version rather than cat VERSION. Not sure if that is possible.

This would be my preference, I think that this PR should not be merged until that is done. Probably this can be something as simple as:

```yaml
    override-pull: |
      cd $SNAPCRAFT_PROJECT_DIR
      if [ -f VERSION ]; then
        PROJECT_VERSION=$(cat VERSION)
      else
        PROJECT_VERSION=local-dev
      fi
      GIT_REVISION=$(git rev-parse --short HEAD)
      snapcraftctl set-version ${PROJECT_VERSION}-$(date +%Y%m%d)+${GIT_REVISION}
```

since the version number for a local build is not super important.

**Comment by ernestojeda** [comment]
I will apply this to my PR

**Comment by jpwhitemn** [comment]
LGTM

**Pull request merged**
