### PR TITLE
Updated scheduler to properly use runOnce intervals for Edinburgh.

### LINKED ISSUE #1444: Get empty reply while POST scheduler with runOnce
While calling scheduler (`interval`) POST API (with no `frequency`), got empty reply from server and go panic in docker logs.
### Reproduce step:
1. Call POST API of scheduler with the CURL command as below:
```
curl -H "Content-Type: application/json" \
-X POST \
-d '{"name": "one-day5", "start": "20190614T081600", "runOnce": true}' \
http://localhost:48085/api/v1/interval
```
2. Will get empty reply from server.
```
curl: (52) Empty reply from server
```

3. Call GET API to check the interval was created.
```
$ curl http://localhost:48085/api/v1/interval/name/one-day5
{"Timestamps":{"created":1560500853210,"modified":1560500853210},"id":"3bc75326-464e-42f7-9c1c-ce4b50a98fc5","name":"one-day5","start":"20190614T081600","runOnce":true}
```
4. Get the following error while calling `docker logs edgex-support-scheduler`::
```
level=INFO ts=2019-06-14T08:27:33.1273061Z app=edgex-support-scheduler source=router.go:127 msg="Posting new Interval: {\"Timestamps\":{},\"name\":\"one-day5\",\"start\":\"20190614T081600\",\"runOnce\":true}"
level=INFO ts=2019-06-14T08:27:33.2052319Z app=edgex-support-scheduler source=schedule.go:114 msg="scheduler could not find interval with interval with name : one-day5"             
2019/06/14 08:27:33 http: panic serving 172.18.0.1:59568: runtime error: index out of range                                                                                          
goroutine 172 [running]:
net/http.(*conn).serve.func1(0xc0003b4960)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0xb0be80, 0x116f1c0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/edgexfoundry/edgex-go/internal/support/scheduler.parseFrequency(0x0, 0x0, 0x11804c0)                                                                                      
        /go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/schedulecontext.go:113 +0x24b                                                                            
github.com/edgexfoundry/edgex-go/internal/support/scheduler.(*IntervalContext).Reset(0xc000104a50, 0x0, 0x0, 0x0, 0xc00015a2d0, 0x24, 0xc00028c658, 0x8, 0xc00028c660, 0xf, ...)     
        /go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/schedulecontext.go:72 +0x1c7                                                                             
github.com/edgexfoundry/edgex-go/internal/support/scheduler.(*QueueClient).AddIntervalToQueue(0x11a0e40, 0x0, 0x0, 0x0, 0xc00015a2d0, 0x24, 0xc00028c658, 0x8, 0xc00028c660, 0xf, ...)
        /go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/schedule.go:141 +0x34c                                                                                   
github.com/edgexfoundry/edgex-go/internal/support/scheduler.addNewInterval(0x0, 0x0, 0x0, 0xc00015a2d0, 0x24, 0xc00028c658, 0x8, 0xc00028c660, 0xf, 0x0, ...)                        
        /go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/interval.go:85 +0x298                                                                                    
github.com/edgexfoundry/edgex-go/internal/support/scheduler.intervalHandler(0xce3840, 0xc00021e460, 0xc0002a9100)                                                                    
        /go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/router.go:129 +0x256                                                                                     
net/http.HandlerFunc.ServeHTTP(0xc1cef8, 0xce3840, 0xc00021e460, 0xc0002a9100)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/edgexfoundry/edgex-go/internal/pkg/correlation.OnRequestBegin.func1(0xce3840, 0xc00021e460, 0xc0002a9100)                                                                 
        /go/src/github.com/edgexfoundry/edgex-go/internal/pkg/correlation/middleware.go:45 +0xa3                                                                                     
net/http.HandlerFunc.ServeHTTP(0xc000292780, 0xce3840, 0xc00021e460, 0xc0002a9100)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/edgexfoundry/edgex-go/internal/pkg/correlation.OnResponseComplete.func1(0xce3840, 0xc00021e460, 0xc0002a9100)                                                             
        /go/src/github.com/edgexfoundry/edgex-go/internal/pkg/correlation/middleware.go:31 +0x9e                                                                                     
net/http.HandlerFunc.ServeHTTP(0xc0002927a0, 0xce3840, 0xc00021e460, 0xc0002a9100)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/edgexfoundry/edgex-go/internal/pkg/correlation.ManageHeader.func1(0xce3840, 0xc00021e460, 0xc0002a9000)                                                                   
        /go/src/github.com/edgexfoundry/edgex-go/internal/pkg/correlation/middleware.go:24 +0x1f0                                                                                    
net/http.HandlerFunc.ServeHTTP(0xc0002927c0, 0xce3840, 0xc00021e460, 0xc0002a9000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00014ac00, 0xce3840, 0xc00021e460, 0xc0002a8e00)                                                                                       
        /go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xd0
github.com/gorilla/context.ClearHandler.func1(0xce3840, 0xc00021e460, 0xc0002a8e00)
        /go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc000292540, 0xce3840, 0xc00021e460, 0xc0002a8e00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc000133110, 0xce3840, 0xc00021e460, 0xc0002a8e00)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0003b4960, 0xce42c0, 0xc000397140)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```
5. Call DELETE API and got `no interval found for id: one-day5` response. The interval entry cannot be deleted.
```
$ curl -X DELETE http://localhost:48085/api/v1/interval/name/one-day5
no interval found for id: one-day5
```

### PR DESCRIPTION
**Pull request by brandonforster**
Fix #1444 for Edinburgh.

Signed-off-by: Brandon Forster <brandonforster@gmail.com>

### CODE REVIEW

**Comment by brandonforster** [comment]
recheck

**Comment by brandonforster** [comment]
recheck

**Comment by tsconn23** [comment]
@lindseysimple Can you please test this PR against the issue you filed and confirm the fix before merge?

**Comment by lindseysimple** [comment]
Hi @tsconn23 I've verified the issue is fixed, thanks.

**Comment by tsconn23** [comment]
Merging. Because of timing, fix will not be deployed until we decide to do a dot release for Edinburgh.

**Pull request merged**
