### PR TITLE
fix(metadata): correct V2 parsing err response

### PR DESCRIPTION
**Pull request by cloudxxx8**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## Issue Number:
Fix https://github.com/edgexfoundry/edgex-go/issues/2769

## What is the new behavior?
V2 add request JSON parsing isn't handeled correctly.  Make them return
the response format meet the swagger definition.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by judehung** [comment]
@cloudxxx8 Please rebase this PR.  Thanks!

**Comment by cloudxxx8** [comment]
recheck

**Review by judehung — APPROVED** [review]
LGTM

**Pull request merged**
