### PR TITLE
feat(snap): add additional tokens for app-service-configurable profiles

### PR DESCRIPTION
**Pull request by siggiskulason**
The external-mqtt-trigger and app-push-to-core profiles are used by the TAF integration tests.

This PR enables those profiles by creating tokens for them and making the tokens available for
the edgex-app-service-configurable snap.

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) n/a
  <link to docs PR>

## Testing Instructions

1. Create a clean build of the snap 
2. Install the snap
3. Confirm the token exists: `sudo ls /var/snap/edgexfoundry/current/secrets/app-external-mqtt-trigger/secrets-token.json`

### CODE REVIEW

**Comment by farshidtz** [comment]
Can't we add this token for the test via the config arguments?
https://github.com/edgexfoundry/edgex-go/tree/main/snap#secret-store-settings-prefix-envsecurity-secret-store

It also applies to `app-functional-tests`.

**Comment by siggiskulason** [comment]
> Can't we add this token for the test via the config arguments? https://github.com/edgexfoundry/edgex-go/tree/main/snap#secret-store-settings-prefix-envsecurity-secret-store
> 
> It also applies to `app-functional-tests`.

Yes, indeed, I can do

```
LIST=`sudo snap get edgexfoundry env.security-secret-store.add-secretstore-tokens`
LIST2=`sudo snap get edgexfoundry env.security-secret-store.add-known-secrets`
sudo snap set edgexfoundry env.security-secret-store.add-secretstore-tokens="$LIST,app-external-mqtt-trigger"
sudo snap set edgexfoundry env.security-secret-store.add-known-secrets="$LIST2,redisdb[app-external-mqtt-trigger]"
sudo snap restart edgexfoundry.security-secretstore-setup 
```
and that generates the token. However, it adds a few extra steps and the requirement to revoke and regenerate all tokens and since this profile is one of the built-in profiles of app-service-configurable, it might make sense to include a token for it by default.

**Comment by siggiskulason** [comment]
I added a 2nd commit to this PR to add the app-push-to-core token as well, so we now have tokens for all 6 built-in profiles.

**Comment by siggiskulason** [comment]
force-pushed a rebase to main

**Review by farshidtz — APPROVED** [review]
Looks good. 

Please update the PR title:
- multiple tokens are added now
- sounds more like a new feature (feat) than fix

**Review by farshidtz — CHANGES_REQUESTED** [review]
Looks good. But please update the PR title:

- multiple tokens are added now
- sounds more like a new feature (feat) than fix

**Comment by siggiskulason** [comment]
> Looks good. But please update the PR title:
> 
> * multiple tokens are added now
> * sounds more like a new feature (feat) than fix

thanks - done.

**Review by farshidtz — APPROVED** [review]
Thanks @siggiskulason.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
