### PR TITLE
fix: Broken Slack invite link in README.md

### LINKED ISSUE #2468: Slack link is invalid in README.md
# 📚 Docs or Wiki Bug Report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://docs.edgexfoundry.org/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

Is there an active slack workspace?

### PR DESCRIPTION
**Pull request by bnevis-i**
Closes #2468

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
recheck

**Comment by ernestojeda** [comment]
recheck

**Pull request merged**
