### PR TITLE
edgex-go pipeline for Geneva release

### PR DESCRIPTION
**Pull request by ernestojeda**
Work in progress pipeline for testing on LF sandbox.

### CODE REVIEW

**Comment by lranjbar** [comment]
We just need to make sure that any changes in ci-management are complete to address the functionality called out in #2331

**Comment by cherrycl** [comment]
The credentialsId: 'swaggerhub-api-key' for posting API to SwaggerHub was created by [LF ticket IT-18875](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-18875).

**Comment by michaelestrin** [comment]
@ernestojeda how do I review this?  Or are you just looking for someone to approve and merge?

**Comment by ernestojeda** [comment]
> @ernestojeda how do I review this? Or are you just looking for someone to approve and merge?

Yes approve and merge. Also just to keep you in the loop about the change.

**Pull request merged**
