### PR TITLE
docs: update readme to reflect steps of latest version by removing pkg…

### LINKED ISSUE #3689: Update the Readme file to reflect the installation steps of the latest version
# 📚 Docs or Wiki Bug Report

### Description

pkg-config is not necessary anymore, so it should be removed from the installation section.

### What's the affected URL?**
https://github.com/edgexfoundry/edgex-go/blob/22189a20601e835d069a8814fe5b33d27e11ca61/README.md

### Expected vs Actual Behavior**
Users should be able to install and deploy by simply following the Readme file.
It causes https://github.com/edgexfoundry/edgex-go/issues/3687

### PR DESCRIPTION
**Pull request by jenmwms**
…-config

Closes #3689

Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?): *Updated documentation.*
- [ ] I have opened a PR for the related docs change (if not, why?)

## Testing Instructions
Follow the README section on prerequisites to build the edgeX-go natively.

### CODE REVIEW

**Review by lenny-intel — DISMISSED** [review]
LGTM

**Comment by cloudxxx8** [comment]
The commit prefix should be `docs`, not `fix`

**Comment by jenmwms** [comment]
Thanks! I'll adjust the commit message prefix. Looks like I need to rebase, too.

**Review by lenny-intel — APPROVED** [review]

**Comment by jenmwms** [comment]
The CI/jenkins is failing but I do not think it is from my PR because I changed the README.md only. Is this a broader issue seen elsewhere?

**Comment by lenny-intel** [comment]
> The CI/jenkins is failing but I do not think it is from my PR because I changed the README.md only. Is this a broader issue seen elsewhere?

No it isn't your PR. When this occurs we submit the `recheck` comment to kick it off again like I just did.

**Comment by lenny-intel** [comment]
recheck

**Pull request merged**
