### PR TITLE
snap/snapcraft.yaml: upgrade go to v1.10.2

### PR DESCRIPTION
**Pull request by anonymouse64**
Dup of https://github.com/edgexfoundry/edgex-go/pull/340 but for california.

### CODE REVIEW

**Comment by anonymouse64** [comment]
This also now upgrades the version of consul to v1.2.0, as a dup of https://github.com/edgexfoundry/edgex-go/pull/332

**Comment by tsconn23** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by anonymouse64** [comment]
Reverted the consul version to v1.1.0

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
@tsconn23 verify-arm working now.

**Pull request merged**
