### PR TITLE
build(snap): Snap remove vault depend consul

### PR DESCRIPTION
**Pull request by jim-wang-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the new behavior?
remove the dependency of consul  from vault

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## New Imports

- [ ] Yes
- [X ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by jim-wang-intel** [comment]
@tonyespy need your help on generating patch due to snpacraft change.

**Review by bnevis-i — APPROVED** [review]
LGTM

**Review by bnevis-i — DISMISSED** [review]
Should probably be under $SNAP_DATA.  vault/file doesn't mean anything to a snap.

**Comment by jim-wang-intel** [comment]
> Should probably be under $SNAP_DATA. vault/file doesn't mean anything to a snap.

This configuration file is in the context of Vault itself, so the path is relative to whatever the installer is doing, we should not dictate  the absolute path here.

**Comment by bnevis-i** [comment]
> This configuration file is in the context of Vault itself, so the path is relative to whatever the installer is doing, we should not dictate the absolute path here.

But in a snap, Vault runs as a service.  There is no "context of Vault".  @tonyespy can you chime in here?

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
> But in a snap, Vault runs as a service. There is no "context of Vault". @tonyespy can you chime in here?

Confirmed by looking at results that in fact, Vault is creating its data files in $SNAP_DATA without explicitly telling it to do so.

**Comment by jim-wang-intel** [comment]
> > But in a snap, Vault runs as a service. There is no "context of Vault". @tonyespy can you chime in here?
> 
> Confirmed by looking at results that in fact, Vault is creating its data files in $SNAP_DATA without explicitly telling it to do so.

worked with Bryon and the snapcraft automatically builds the vault's data under $SNAP_DATA so vault can handle it from the vault's configuration based on their backend file system.

**Comment by tonyespy** [comment]
> > But in a snap, Vault runs as a service. There is no "context of Vault". @tonyespy can you chime in here?
> 
> Confirmed by looking at results that in fact, Vault is creating its data files in $SNAP_DATA without explicitly telling it to do so.

Before this change was made, afaik vault didn't persist any data to disk. The vault configuration file is copied by the snap install hook (see `snap/hooks/install`) from `snap/local/runtime-helpers/config/security-secret-store/vault-config.hcl.in` to `$SNAP_DATA/config/security-secret-store/vault-config.hcl`.

Note, this file is also modified by the snap install hook to replace references to `$SNAP_DATA` with fully qualified paths (e.g. `/var/snap/edgexfoundry/current/...`). The only keys in the configuration files that are replaced are those relating to the TLS configuration.

With this change (i.e. switching the backend to use the filesystem instead of consul) vault will need to be told to use a directory under `$SNAP_DATA` for persistence. To do this we just need to update the value of path in `vault-config.hcl.in` to use `$SNAP_DATA`. Ex.

`path = "$SNAP_DATA/vault/file"
`
Depending on whether `path` is the path to the directory vault uses for persistence, or the actual file it uses for persistence (in which case I'd argue for a better name), the install hook may need to be modified to create one or more directories under `$SNAP_DATA`.

**Comment by jim-wang-intel** [comment]
> > > But in a snap, Vault runs as a service. There is no "context of Vault". @tonyespy can you chime in here?
> > 
> > 
> > Confirmed by looking at results that in fact, Vault is creating its data files in $SNAP_DATA without explicitly telling it to do so.
> 
> Before this change was made, afaik vault didn't persist any data to disk. The vault configuration file is copied by the snap install hook (see `snap/hooks/install`) from `snap/local/runtime-helpers/config/security-secret-store/vault-config.hcl.in` to `$SNAP_DATA/config/security-secret-store/vault-config.hcl`.
> 
> Note, this file is also modified by the snap install hook to replace references to `$SNAP_DATA` with fully qualified paths (e.g. `/var/snap/edgexfoundry/current/...`). The only keys in the configuration files that are replaced are those relating to the TLS configuration.
> 
> With this change (i.e. switching the backend to use the filesystem instead of consul) vault will need to be told to use a directory under `$SNAP_DATA` for persistence. To do this we just need to update the value of path in `vault-config.hcl.in` to use `$SNAP_DATA`. Ex.
> 
> `path = "$SNAP_DATA/vault/file" `
> Depending on whether `path` is the path to the directory vault uses for persistence, or the actual file it uses for persistence (in which case I'd argue for a better name), the install hook may need to be modified to create one or more directories under `$SNAP_DATA`.

Thanks, Tony @tonyespy.  I've tested the `vault/file` in the configuration as it is and did a snapcraft build and ran the snap edgexfoundry locally and it appears snapcraft built it automatically into $SNAP_DATA so the `vault/file` works. 

```sh
root@jim-NUC7i5DNHE:/# find / -name "_mounts"
find: ‘/run/user/1000/gvfs’: Permission denied
/var/snap/edgexfoundry/x1/vault/file/core/_mounts
```

The log messages of running snap edgexfoundry.vault:

```sh
jim@jim-NUC7i5DNHE:~/go/src/github.com/edgexfoundry/edgex-go$ sudo snap logs -n=all edgexfoundry.vault

2020-12-11T00:32:59Z systemd[1]: Started Service for snap application edgexfoundry.vault.
2020-12-11T00:33:01Z edgexfoundry.vault[15920]: ==> Vault server configuration:
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:                      Cgo: disabled
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:               Go Version: go1.15.2
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:               Listener 1: tcp (addr: "localhost:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:                Log Level: info
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:                    Mlock: supported: true, enabled: true
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:            Recovery Mode: false
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:                  Storage: file
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:                  Version: Vault v1.5.4
2020-12-11T00:33:01Z edgexfoundry.vault[15920]:              Version Sha: 1a730771ec70149293efe91e1d283b10d255c6d1+CHANGES
2020-12-11T00:33:01Z edgexfoundry.vault[15920]: ==> Vault server started! Log data will stream in below:
2020-12-11T00:33:01Z edgexfoundry.vault[15920]: 2020-12-10T17:33:00.998-0700 [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2020-12-11T00:33:01Z edgexfoundry.vault[15920]: 2020-12-10T17:33:00.998-0700 [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.563-0700 [INFO]  core: security barrier not initialized
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.568-0700 [INFO]  core: security barrier not initialized
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.576-0700 [INFO]  core: security barrier initialized: stored=1 shares=5 threshold=3
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.578-0700 [INFO]  core: post-unseal setup starting
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.628-0700 [INFO]  core: loaded wrapping token key
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.628-0700 [INFO]  core: successfully setup plugin catalog: plugin-directory=
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.628-0700 [INFO]  core: no mounts; adding default mount table
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.631-0700 [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.631-0700 [INFO]  core: successfully mounted backend: type=system path=sys/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.632-0700 [INFO]  core: successfully mounted backend: type=identity path=identity/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.636-0700 [INFO]  core: successfully enabled credential backend: type=token path=token/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.636-0700 [INFO]  core: restoring leases
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.636-0700 [INFO]  rollback: starting rollback manager
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.636-0700 [INFO]  expiration: lease restore complete
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.637-0700 [INFO]  identity: entities restored
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.637-0700 [INFO]  identity: groups restored
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.637-0700 [INFO]  core: usage gauge collection is disabled
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.637-0700 [INFO]  core: post-unseal setup complete
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.638-0700 [INFO]  core: root token generated
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.639-0700 [INFO]  core: pre-seal teardown starting
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.640-0700 [INFO]  rollback: stopping rollback manager
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.641-0700 [INFO]  core: pre-seal teardown complete
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.644-0700 [INFO]  core.cluster-listener.tcp: starting listener: listener_address=127.0.0.1:8201
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.644-0700 [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.644-0700 [INFO]  core: post-unseal setup starting
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.644-0700 [INFO]  core: loaded wrapping token key
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.644-0700 [INFO]  core: successfully setup plugin catalog: plugin-directory=
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.645-0700 [INFO]  core: successfully mounted backend: type=system path=sys/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.645-0700 [INFO]  core: successfully mounted backend: type=identity path=identity/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.645-0700 [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  core: successfully enabled credential backend: type=token path=token/
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  core: restoring leases
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  rollback: starting rollback manager
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  identity: entities restored
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  identity: groups restored
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  expiration: lease restore complete
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  core: usage gauge collection is disabled
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  core: post-unseal setup complete
2020-12-11T00:33:09Z edgexfoundry.vault[15920]: 2020-12-10T17:33:09.647-0700 [INFO]  core: vault is unsealed
2020-12-11T00:33:10Z edgexfoundry.vault[15920]: 2020-12-10T17:33:10.654-0700 [INFO]  core: root generation initialized: nonce=6f8e5971-8ff1-3478-4782-04ee7f0c3d4f
2020-12-11T00:33:10Z edgexfoundry.vault[15920]: 2020-12-10T17:33:10.662-0700 [INFO]  core: root generation finished: nonce=6f8e5971-8ff1-3478-4782-04ee7f0c3d4f
2020-12-11T00:33:10Z edgexfoundry.vault[15920]: 2020-12-10T17:33:10.688-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/root/h41eeba15d198249f2b90eb85f9b1e0264f7c7a57b1762c1219482b14c92ae744
2020-12-11T00:33:10Z edgexfoundry.vault[15920]: 2020-12-10T17:33:10.989-0700 [INFO]  core: successful mount: namespace= path=secret/ type=kv
2020-12-11T00:33:11Z edgexfoundry.vault[15920]: 2020-12-10T17:33:11.000-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/h83c22cb62cfb44c1549b1e417a6ecc75165b4ca8ab6161b46ecf47f2b50c62a9
2020-12-11T00:33:11Z edgexfoundry.vault[15920]: 2020-12-10T17:33:11.002-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/root/h086175a977f91033abf3e813354f0867ab14d2a0c24129db05707fec06472da3
2020-12-11T01:33:10Z edgexfoundry.vault[15920]: 2020-12-10T18:33:10.960-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/h11a944cf86f4bcf1eb8392293b0e1bdc76add6693fcb544a44861ff4de51e643
2020-12-11T01:33:10Z edgexfoundry.vault[15920]: 2020-12-10T18:33:10.964-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/h5040795921e1dde19d13239d34eb0037dc10fd5f6b4b7b8272f99b7aef0c1d40
2020-12-11T01:33:10Z edgexfoundry.vault[15920]: 2020-12-10T18:33:10.969-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/hee21a339334dae81a493fa8546bd7cbaba9c30eb8470961f7a2965f482df9f9f
2020-12-11T01:33:10Z edgexfoundry.vault[15920]: 2020-12-10T18:33:10.977-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/h775c6469309a6448a3e3cdfa371f3a7e1df7907d5dc28cb6f8ff55e2d79c32f5
2020-12-11T01:33:10Z edgexfoundry.vault[15920]: 2020-12-10T18:33:10.980-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/h2184d9fa62829d5c8916b133b87492b1a3b5b384db52ffa1c1727254b403b701
2020-12-11T01:33:10Z edgexfoundry.vault[15920]: 2020-12-10T18:33:10.983-0700 [INFO]  expiration: revoked lease: lease_id=auth/token/create/h51a0184d2f5f81ed48c79b9b95acb2d5a5f30409fb139ec1f4dbc3c42
```

**Comment by bnevis-i** [comment]
> Note, this file is also modified by the snap install hook to replace references to `$SNAP_DATA` with fully qualified paths (e.g. `/var/snap/edgexfoundry/current/...`). The only keys in the configuration files that are replaced are those relating to the TLS configuration.

@tonyespy Why is this important?

**Comment by bnevis-i** [comment]
> Before this change was made, afaik vault didn't persist any data to disk.

It used Consul for storage.

**Comment by tonyespy** [comment]
> > Note, this file is also modified by the snap install hook to replace references to `$SNAP_DATA` with fully qualified paths (e.g. `/var/snap/edgexfoundry/current/...`). The only keys in the configuration files that are replaced are those relating to the TLS configuration.
> 
> @tonyespy Why is this important?

I was trying to figure out how vault's filesystem plugin worked. The "path" attribute being set is supposed to be an absolute path via the documentation for the [filesystem storage backend documentation](https://www.vaultproject.io/docs/configuration/storage/filesystem).

I think what's going on though is that the filesystem storage backend uses `os.OpenFile` to create new files, and when given a relative path, if appends it to the current working dir, which in this case is `$SNAP_DATA`.  So I think things are OK "as is".

That said, I did stumble across this nugget in the filesystem storage plugin:

```
// FileBackend is a physical backend that stores data on disk
// at a given file path. It can be used for durable single server
// situations, or to develop locally where durability is not critical.
//
// WARNING: the file backend implementation is currently extremely unsafe
// and non-performant. It is meant mostly for local testing and development.
// It can be improved in the future.
```

**Review by tonyespy — COMMENTED** [review]
I think this change is OK, but I would like to discuss next week before I approve.

> @tonyespy Why is this important?

I was trying to figure out how vault's filesystem plugin worked. The "path" attribute being set is supposed to be an absolute path via the documentation for the [filesystem storage backend documentation](https://www.vaultproject.io/docs/configuration/storage/filesystem).

I think what's going on though is that the filesystem storage backend uses `os.OpenFile` to create new files, and when given a relative path, if appends it to the current working dir, which in this case is `$SNAP_DATA`.  So I think things are OK "as is".

That said, I did stumble across this nugget in the filesystem storage plugin:

```
// FileBackend is a physical backend that stores data on disk
// at a given file path. It can be used for durable single server
// situations, or to develop locally where durability is not critical.
//
// WARNING: the file backend implementation is currently extremely unsafe
// and non-performant. It is meant mostly for local testing and development.
// It can be improved in the future.
```

I think this comment warrants some investigation...

**Comment by bnevis-i** [comment]
> > @tonyespy Why is this important?
> 
> I was trying to figure out how vault's filesystem plugin worked. The "path" attribute being set is supposed to be an absolute path via the documentation for the [filesystem storage backend documentation]

Actually, I was referring specifically to: "replace references to $SNAP_DATA with fully qualified paths".  For arguments' sake, if $SNAP_DATA were evaluated at runtime, would that be a problem?   I noticed that on Jims system, the path ended up as `.../edgexfoundry/x1` but your say you substitute `.../edgexfoundry/current`  Is there something subtle going on here.

**Comment by bnevis-i** [comment]
> ```
> // FileBackend is a physical backend that stores data on disk
> // at a given file path. It can be used for durable single server
> // situations, or to develop locally where durability is not critical.
> //
> // WARNING: the file backend implementation is currently extremely unsafe
> // and non-performant. It is meant mostly for local testing and development.
> // It can be improved in the future.
> ```
> 
> I think this comment warrants some investigation...

I agree.  Durability of writes and consistency is something that file system implementers work hard at.  In fact, there is no such warning on the S3 backend provider, and S3 is well documented to not implement a strong consistency model!  Perhaps Vault doesn't handle concurrency on the file store, and expect people to use things like databases that do concurrency by design.

**Comment by jim-wang-intel** [comment]
> > > @tonyespy Why is this important?
> > 
> > 
> > I was trying to figure out how vault's filesystem plugin worked. The "path" attribute being set is supposed to be an absolute path via the documentation for the [filesystem storage backend documentation]
> 
> Actually, I was referring specifically to: "replace references to $SNAP_DATA with fully qualified paths". For arguments' sake, if $SNAP_DATA were evaluated at runtime, would that be a problem? I noticed that on Jims system, the path ended up as `.../edgexfoundry/x1` but your say you substitute `.../edgexfoundry/current` Is there something subtle going on here.

@bnevis-i    the `current` in my system is actually a symbolic link pointing to `x1` (current -> x1 );  so they are the same I guess

**Comment by tonyespy** [comment]
> > > @tonyespy Why is this important?
> > 
> > 
> > I was trying to figure out how vault's filesystem plugin worked. The "path" attribute being set is supposed to be an absolute path via the documentation for the [filesystem storage backend documentation]
> 
> Actually, I was referring specifically to: "replace references to $SNAP_DATA with fully qualified paths". For arguments' sake, if $SNAP_DATA were evaluated at runtime, would that be a problem? 

No. That said, you can't guarantee that environment variables in configuration files will always be evaluated at runtime (e.g. our own `configuration.toml files`). If you know for sure that they are, then leaving the `$SNAP_DATA` (or `$SNAP_COMMON`) in the file(s) is fine.

> I noticed that on Jims system, the path ended up as `.../edgexfoundry/x1` but your say you substitute `.../edgexfoundry/current` Is there something subtle going on here.

As @jim-wang-intel pointed out, **current** is a symbolic link to the actual revision-specific directory. The per-revision versioning of `$SNAP_DATA` is one of the mechanisms which allow snap refreshes (our term for updates) to be transactional, and thus support proper rollback.

**Comment by bnevis-i** [comment]
@tonyespy I have posted a question the HashiCorp forums asking whether the "file" backend is suitable for production usage in a single node scenario as implied by the documentation, or will scramble your data as implied by the code.  Let's see what they say.

**Review by Salemsa89 — APPROVED** [review]

**Comment by jim-wang-intel** [comment]
> I think this change is OK, but I would like to discuss next week before I approve.
> 
> > @tonyespy Why is this important?
> 
> I was trying to figure out how vault's filesystem plugin worked. The "path" attribute being set is supposed to be an absolute path via the documentation for the [filesystem storage backend documentation](https://www.vaultproject.io/docs/configuration/storage/filesystem).
> 
> I think what's going on though is that the filesystem storage backend uses `os.OpenFile` to create new files, and when given a relative path, if appends it to the current working dir, which in this case is `$SNAP_DATA`. So I think things are OK "as is".
> 
> That said, I did stumble across this nugget in the filesystem storage plugin:
> 
> ```
> // FileBackend is a physical backend that stores data on disk
> // at a given file path. It can be used for durable single server
> // situations, or to develop locally where durability is not critical.
> //
> // WARNING: the file backend implementation is currently extremely unsafe
> // and non-performant. It is meant mostly for local testing and development.
> // It can be improved in the future.
> ```
> 
> I think this comment warrants some investigation...

Hi @tonyespy, I've changed to use "raft" storage as backend of Vault now.  See if this works for you.  Thanks.

**Comment by jim-wang-intel** [comment]
After discussion in Security WG at 12/16/2020, we decided to use "file" as the Vault's backend for now. Rebased and dropped the previous commit.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
