### PR TITLE
Removed obsolete "prepare" target from Makefile

### PR DESCRIPTION
**Pull request by tsconn23**
#1275

Signed-off-by: Trevor Conn <trevor_conn@dell.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
@jamesrgregg Error from builds
```
16:36:25 Step 10/30 : RUN make prepare
16:36:25  ---> Running in 788a064e4998
16:36:26 [91mmake: *** No rule to make target 'prepare'.  Stop.
16:36:26 [0mThe command '/bin/sh -c make prepare' returned a non-zero code: 2
16:36:27 make: *** [docker_config_seed] Error 2
16:36:27 Build step 'Execute shell' marked build as failure
```
Looks like Jenkins is still expecting this.

**Comment by ernestojeda** [comment]
recheck

**Comment by ernestojeda** [comment]
@tsconn23 It looks like the `make prepare` is still being referenced in the `cmd/config-seed/Dockerfile`. (https://github.com/tsconn23/edgex-go/blob/issue_1275/cmd/config-seed/Dockerfile#L40) You will have to remove it from that file as well.

**Comment by anonymouse64** [comment]
It would be awesome if you also applied this patch on top of this PR to fix snap builds after this is merged :smile: 

```patch
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index eb68567b..de57fd51 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -414,7 +414,6 @@ parts:
       . $SNAPCRAFT_STAGE/bin/go-build-helper.sh
       gopartbootstrap github.com/edgexfoundry/edgex-go
 
-      make prepare
       make build
 
       install -DT "./cmd/core-command/core-command" "$SNAPCRAFT_PART_INSTALL/bin/core-command"
```

**Comment by tsconn23** [comment]
@anonymouse64 done

**Comment by anonymouse64** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Pull request merged**
