### PR TITLE
Duplicated support-logging

### PR DESCRIPTION
**Pull request by chenchix**
Signed-off-by: chencho <smunoz@cavium.com>

### CODE REVIEW

**Comment by drasko** [comment]
Why is this a duplicate? Is support logging started by some other service implicitly?

**Comment by chenchix** [comment]
@drasko i added it in my merge by mistake at the end of the script

**Comment by drasko** [comment]
I do not see it in the end of the script, I see only one occurrence. This is why I am asking.

**Comment by chenchix** [comment]
Current version  (merged in the last PR) has both support-logging script calls, https://github.com/edgexfoundry/edgex-go/blob/master/bin/edgex-launch.sh

This is why I have removed now.

**Comment by feclare** [comment]
It is being launched the first and the fifth 
https://github.com/edgexfoundry/edgex-go/blob/master/bin/edgex-launch.sh

**Pull request merged**
