### PR TITLE
feat(metadata): implement PATCH device profile basic info API 

### PR DESCRIPTION
**Pull request by hahattan**
**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) already addressed in #3919
  <link to docs PR>

## Testing Instructions

1. run metadata from this branch
2. verify  PATCH `/api/v2/deviceprofile/basicinfo` is functioning

(dependent on https://github.com/edgexfoundry/go-mod-core-contracts/pull/715)

### CODE REVIEW

**Comment by hahattan** [comment]
recheck

**Review by cloudxxx8 — DISMISSED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@hahattan please update go.mod and go.sum to resolve the conflict

**Review by cloudxxx8 — DISMISSED** [review]
LGTM

**Review by lenny-intel — COMMENTED** [review]
LGTM, please complete PR template, i.e. why link to docs PR not provided.

**Review by cloudxxx8 — APPROVED** [review]
The PR template just completed

**Pull request merged**
