### PR TITLE
style: Enable gosimple linter and associated recommendations

### PR DESCRIPTION
**Pull request by bnevis-i**
See #3565

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) Not adding functionality.
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)  Ran unit test suite.
- [ ] I have opened a PR for the related docs change (if not, why?) Not applicable.

## Testing Instructions
Ran "make test" suite.  Ran make docker and started framework.

### CODE REVIEW

**Comment by bnevis-i** [comment]
recheck

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
Resolved merge conflicts

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
