### PR TITLE
build(snap): upgrade third-party dependencies

### PR DESCRIPTION
**Pull request by farshidtz**
This PR upgrades the 3rd party services of the edgexfoundry snap. 

part |  latest stable | current docker | snap | source
-- | -- | -- | -- | --
vault | 1.8.5 | 1.8.4 | ~1.7.2~ 1.8.5 | ~git~ prebuilt archive
consul | 1.10.4 | 1.10.3 | ~1.9.5~ 1.10.4 | prebuilt archive
redis | 6.2.6 | 6.2.6 | ~6.2.4~ 6.2.6 | git
kong | 2.6.0 | 2.5.1 | ~2.4.1~ 2.6.0 | deb archive
kuiper | 1.3.1 | 1.3.1 | ~1.3.0~ 1.3.1 | git
postgres | 10.19 / 13.5 / 14.1 | 13.4 | 10.19 | deb archive

Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
Checkbox tests pass.
TAF functional tests pass with similar failure rate: 17/501 (4/138 support notification, 1/69 support scheduler, 12/16 system agent)

```
git clone https://github.com/farshidtz/edgex-go.git -b snap-dep-upgrade
cd edgex-go
snapcraft

sudo snap install edgexfoundry_xxx.snap --dangerous
```

Check the logs
Do smoke testing for updates services

### CODE REVIEW

**Comment by farshidtz** [comment]
@siggiskulason @MonicaisHer please review.

**Review by siggiskulason — APPROVED** [review]
LGTM
a) checked logs and confirmed versions are as expected: (journalctl -g version -n 1000 )
- edgexfoundry.vault[140821]:                  Version: Vault v1.8.5
- edgexfoundry.consul[140889]:            Version: '1.10.4'
- edgexfoundry.redis[141235]:  Redis version=6.2.6, bits=64, commit=4930d19e, modified=0, pid=141235, just started
- edgexfoundry.kong-daemon[141182]:  [verbose] Kong: 2.6.0
- edgexfoundry.kuiper[142539]: Serving kuiper (version - 1.3.1) on port 20498, and restful api on http://localhost:59720.

- sudo edgexfoundry.psql --version : psql (PostgreSQL) 10.19 (Ubuntu 10.19-0ubuntu0.18.04.1)

b) ran TAF tests - results as expected

c) smoke-tested Kuiper using checkbox test: ok (installed mosquitto first).

**Comment by siggiskulason** [comment]
@MonicaisHer mentioned seeing 

```
Nov 16 12:06:29 sidar-XPS-8930 edgexfoundry.consul[297166]: 2021-11-16T12:06:29.662Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No cluster leader"
Nov 16 12:06:40 sidar-XPS-8930 edgexfoundry.consul[297166]: 2021-11-16T12:06:40.526Z [ERROR] agent.http: Request error: method=GET url=/v1/acl/policy/name/edgex-service-policy from=127.0.0.1:38202 error="ACL not found"
Nov 16 12:06:40 sidar-XPS-8930 edgexfoundry.consul[297166]: 2021-11-16T12:06:40.549Z [ERROR] agent.http: Request error: method=GET url=/v1/acl/policy/name/edgex-agent-policy from=127.0.0.1:38202 error="ACL not found"
```

on startup. I see those as well, but they happen during consul bootstrap and are then followed by messages indicating the ACL has been set up. Following that I can login to localhost:8500 using the token at /var/snap/edgexfoundry/x1/secrets/consul-acl-token/bootstrap_token.json so consul passes a smoke-test

**Comment by farshidtz** [comment]
@siggiskulason This is probably some internal issue with Consul as it is serving requests before reading the ACL file. We write the ACL file before starting consul: https://github.com/edgexfoundry/edgex-go/blob/387e8ab1d15ec838323413725d11a2640c18939f/snap/local/runtime-helpers/bin/start-consul.sh#L19

I suggest we ignore this here as it isn't introduced by this PR and doesn't affect functionality. It deserves further investigation and a new issue if it turns out to be edgex related.

**Comment by MonicaisHer** [comment]
|part | latest stable | current docker | snap | source|manually test| test note|
|--- | --- | --- | --- | ---| ---| ---|
|vault | 1.8.5 | 1.8.4 | 1.7.2 1.8.5 | git prebuilt archive|PASSED|`postgres` `Redis` `kong` can be started. No error shows in `journalctl`|
|consul | 1.10.4 | 1.10.3 | 1.9.5 1.10.4 | prebuilt archive| | ACL issue needs further investigation|
|redis | 6.2.6 | 6.2.6 | 6.2.4 6.2.6 | git|PASSED| turn on device-virtual, and from edgex-ui data center, where events saved to Redis Database by core data, events can be observed.|
|kong | 2.6.0 | 2.5.1 | 2.4.1 2.6.0 | deb archive|PASSED|1. validate that by default a self-signed cert is being used for TLS; 2. validate CA-signed TLS certificate can be used for TLS.|
|kuiper | 1.3.1 | 1.3.1 | 1.3.0 1.3.1 | git|PASSED|1. when enable/disable Kuiper and ensures that both Kuiper and app-service-configurable are started/stopped;2. ensure Kuiper can create a stream from edgex source;3. ensure Kuiper can create a type of rule with log sink, or a type of rule with MQTT sink;4. validate the operation of stream and rule (status, stop, delete).|
|postgres | 10.19 / 13.5 / 14.1 | 13.4 | 10.19 | deb archive|PASSED| validate postgres is listening on IPv4 address "127.0.0.1", port 5432 (kong-DB) ||

**Review by MonicaisHer — APPROVED** [review]
LGTM

**Pull request merged**
