### PR TITLE
Update link to core-data.raml file

### PR DESCRIPTION
**Pull request by mhall119**
Update link to core-data.raml file to point to the correct location

### CODE REVIEW

**Comment by tsconn23** [comment]
@mhall119 Sign-off is missing. 

https://wiki.edgexfoundry.org/display/FA/Contributor+Process.

Scroll down to the yellow section.

**Comment by mhall119** [comment]
I made the edit via Github's web UI, is there a way to do the equivalent step through the same UI?

**Comment by tsconn23** [comment]
@mhall119 Nope.

**Comment by mhall119** [comment]
@tsconn23 better now?

**Pull request merged**
