### PR TITLE
Fix nil panic when configuration.toml can't be loaded.

### LINKED ISSUE #1814: panic running security-secretstore-setup and security-proxy-setup
# 🐞 Bug Report

Running security-secretstore-setup with res/configuration.toml missing causes a panic due to undefined LoggingClient.

See:

```
./security-secretstore-setup --init=true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8a5ae4]

goroutine 17 [running]:
github.com/edgexfoundry/edgex-go/internal/pkg/config.LoadFromFile(0x0, 0x0, 0x0, 0x0, 0x8e1480, 0xc0000b3d40, 0x5d8a5505, 0xc0223daddb)
        /home/ijohnson/git/edgex/edgex-go/internal/pkg/config/loader.go:52 +0x214
github.com/edgexfoundry/edgex-go/internal/security/secretstore.initializeConfiguration(0xbf5ab321623dad00, 0x0, 0x0, 0x0, 0x0, 0xe47d20, 0xe47d01, 0x1)
        /home/ijohnson/git/edgex/edgex-go/internal/security/secretstore/init.go:68 +0x78
github.com/edgexfoundry/edgex-go/internal/security/secretstore.Retry(0xc000140100, 0x0, 0x0, 0x0, 0x0, 0x7530, 0xc00013c050, 0xc0001401e0)
        /home/ijohnson/git/edgex/edgex-go/internal/security/secretstore/init.go:37 +0x131
created by github.com/edgexfoundry/edgex-go/internal/pkg/startup.Bootstrap
        /home/ijohnson/git/edgex/edgex-go/internal/pkg/startup/bootstrap.go:37 +0xe4
```

This is because the LoggingClient in LoadFromFile is nil because we haven't been able to load the configuration file at this point in time yet.

### Affected Services

The issue is located in: security-secretstore-setup

### Is this a regression?

Maybe...

This was from master @ abc9af1de59ab5c4130efe3914aaf2c6688b4e14

### PR DESCRIPTION
**Pull request by bnevis-i**
Fix nil panic when configuration.toml can't be loaded.

Fixes #1814 (cherry-pick from fuji branch)

When configuration.toml can't be loaded, the
LoggingClient global variable isn't initialized,
causing main program to panic when it attempts
to log that configuration.toml can't be loaded.

This is a temporary workaround until security-proxy-setup
is migrated to the common bootstrap.

Duplicate of #2054 for master

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
recheck

**Comment by bnevis-i** [comment]
recheck

**Comment by bnevis-i** [comment]
Keep in mind this is a temporary workaround this is integrated with the common bootstrap.  The common bootstrap will handle setting up the logging object.

**Comment by tsconn23** [comment]
recheck

**Pull request merged**
