### PR TITLE
Remove code obsoleted by common bootstrap package

### PR DESCRIPTION
**Pull request by michaelestrin**
Partial clean up (telemetry code).

https://github.com/edgexfoundry/edgex-go/issues/1811

Signed-off-by: Michael Estrin <m.estrin@dell.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
Rebased

**Comment by michaelestrin** [comment]
Rebased

**Comment by michaelestrin** [comment]
Rebased

**Comment by tsconn23** [comment]
recheck

**Pull request merged**
