### PR TITLE
docs:  fix wrong link of api walk through page

### PR DESCRIPTION
**Pull request by soolaugust**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

current link is not accessible

## What is the new behavior?

update to correct link

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@soolaugust thanks for correcting this. however, you have to sign-off the commit, or the DCO cannot be passed

**Comment by soolaugust** [comment]
@cloudxxx8 thanks for your advice, the change has been applied. please re-check it, thanks

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
