### PR TITLE
Spread the EdgeX MSM API to the CoreData service.

### PR DESCRIPTION
**Pull request by akramtexas**
- This PR contains the work done under the purview of: [Issue Number 648](https://github.com/edgexfoundry/edgex-go/issues/648)
- The essence of this work is to have the EdgeX MSM API be applied to the CoreData service.
- Details can be found here: [Issue Number 648](https://github.com/edgexfoundry/edgex-go/issues/648)

### CODE REVIEW

**Comment by akramtexas** [comment]
> Response to visiting the URL http://localhost:48090/api/v1/config/edgex-support-notifications,edgex-core-command,edgex-core-data was as follows:

`{
    "Configuration": {
        "edgex-core-command": {
            "Clients": {
                "Logging": {
                    "Host": "localhost",
                    "Port": 48061,
                    "Protocol": "http"
                },
                "Metadata": {
                    "Host": "localhost",
                    "Port": 48081,
                    "Protocol": "http"
                }
            },
            "Databases": null,
            "Logging": {
                "EnableRemote": false,
                "File": "./logs/edgex-core-command.log"
            },
            "Registry": {
                "Host": "localhost",
                "Port": 8500,
                "Type": "consul"
            },
            "Service": {
                "BootTimeout": 30000,
                "CheckInterval": "10s",
                "ClientMonitor": 15000,
                "Host": "localhost",
                "Port": 48082,
                "Protocol": "http",
                "ReadMaxLimit": 100,
                "StartupMsg": "This is the Core Command Microservice",
                "Timeout": 5000
            }
        },
        "edgex-core-data": {
            "Clients": {
                "Logging": {
                    "Host": "localhost",
                    "Port": 48061,
                    "Protocol": "http"
                },
                "Metadata": {
                    "Host": "localhost",
                    "Port": 48081,
                    "Protocol": "http"
                }
            },
            "Databases": {
                "Primary": {
                    "Host": "localhost",
                    "Name": "coredata",
                    "Password": "",
                    "Port": 27017,
                    "Timeout": 5000,
                    "Type": "mongodb",
                    "Username": ""
                }
            },
            "DeviceUpdateLastConnected": false,
            "Logging": {
                "EnableRemote": false,
                "File": "./logs/edgex-core-data.log"
            },
            "MessageQueue": {
                "Host": "*",
                "Port": 5563,
                "Protocol": "tcp",
                "Type": "zero"
            },
            "MetaDataCheck": false,
            "PersistData": true,
            "Registry": {
                "Host": "localhost",
                "Port": 8500,
                "Type": "consul"
            },
            "Service": {
                "BootTimeout": 30000,
                "CheckInterval": "10s",
                "ClientMonitor": 15000,
                "Host": "localhost",
                "Port": 48080,
                "Protocol": "http",
                "ReadMaxLimit": 100,
                "StartupMsg": "This is the Core Data Microservice",
                "Timeout": 5000
            },
            "ServiceUpdateLastConnected": false,
            "ValidateCheck": false
        },
        "edgex-support-notifications": {
            "Clients": {
                "Logging": {
                    "Host": "localhost",
                    "Port": 48061,
                    "Protocol": "http"
                }
            },
            "Databases": {
                "Primary": {
                    "Host": "localhost",
                    "Name": "notifications",
                    "Password": "",
                    "Port": 27017,
                    "Timeout": 5000,
                    "Type": "mongodb",
                    "Username": ""
                }
            },
            "Logging": {
                "EnableRemote": false,
                "File": "./logs/edgex-support-notifications.log"
            },
            "Registry": {
                "Host": "localhost",
                "Port": 8500,
                "Type": "consul"
            },
            "ResendLimit": 2,
            "Service": {
                "BootTimeout": 30000,
                "CheckInterval": "10s",
                "ClientMonitor": 15000,
                "Host": "localhost",
                "Port": 48060,
                "Protocol": "http",
                "ReadMaxLimit": 1000,
                "StartupMsg": "This is the Support Notifications Microservice",
                "Timeout": 5000
            },
            "Smtp": {
                "Host": "smtp.gmail.com",
                "Password": "mypassword",
                "Port": 587,
                "Sender": "jdoe@gmail.com",
                "Subject": "EdgeX Notification"
            }
        }
    }
}`

**Comment by tsconn23** [comment]
Per discussion with @akramtexas I am waiting to review this PR until such time as @jduranf 's work in #683 is taken into consideration. If we take the approach indicated by Joan, we'll probably need to close and re-open this PR after some rework.

**Comment by akramtexas** [comment]
- As planned, I did (first thing this Tuesday morning) review the pattern (i.e. the work Joan did on the client) for potential use in our MSM work (The ARM build check is failing still...).
- I like the simplifying aspects. My only concern is the _timing_ of incorporating Joan's work. Will we run into any unforeseeable issue(s) while doing so? The somewhat-less-elegant approach that's currently in place has the benefit of being tested, tried, and true.
- My suggestion is to tag this as a nice-to-have enhancement and defer it to post-Delhi Release backlog 👍

**Comment by tsconn23** [comment]
Closing this PR. As discussed this morning, #683 changes our approach. Expecting a different PR to replace this one.

**Comment by akramtexas** [comment]
- The plan is for the work done in this PR to be reverted (out of the master branch).

**Pull request closed without merging**
