### PR TITLE
feat(data): Implement DELETE /event/device/name/{name} V2 API

### PR DESCRIPTION
**Pull request by judehung**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## Issue Number:
#2837 

## What is the new behavior?
Implement DELETE /event/device/name/{name} for V2 API.  The current V2 API doc still lists DELETE /event/device/{deviceId}; however, as https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/event.go#L14 will be updated to DeviceName instead of DeviceId and https://github.com/edgexfoundry/go-mod-core-contracts/commit/f996e2743d3de620a85ced65e1f97de83f30dc4a updated the route as well, the V2 API spec shall be updated to reflect this change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cloudxxx8** [comment]
please change to DELETE /event/device/{deviceName} and also update the swagger file

**Comment by judehung** [comment]
> please change to DELETE /event/device/{deviceName} and also update the swagger file

Per https://github.com/edgexfoundry/go-mod-core-contracts/commit/f996e2743d3de620a85ced65e1f97de83f30dc4a, the route shall be updated to DELETE /event/device/name/{name}?

**Comment by judehung** [comment]
rebased

**Comment by judehung** [comment]
Close this PR as https://github.com/edgexfoundry/edgex-go/pull/2874 will replace this one.

**Pull request closed without merging**
