### PR TITLE
Fix the incorrect Redis command names (master)

### LINKED ISSUE #2064: Incorrect Redis command names
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
edgex-go/internal/pkg/db/redis/queries.go
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/queries.go#L117
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/queries.go#L122

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Edinburgh
https://github.com/edgexfoundry/edgex-go/blob/edinburgh/internal/pkg/db/redis/queries.go#L115

### Description and Minimal Reproduction
The commands to get the specified range of elements in the sorted set in Redis should be "ZRANGE" and "ZREVRANGE"

Reference:
 - https://redis.io/commands/zrange
 - https://redis.io/commands/zrevrange
## 🔥 Exception or Error
<pre><code>

level=ERROR ts=2019-11-04T11:16:37.037073663Z app=edgex-support-scheduler source=loader.go:65 msg="failed connecting to metadata and retrieving intervals:ERR unknown command `RANGE`, with args beginning with: `interval`, `0`, `-1`, "
level=ERROR ts=2019-11-04T11:16:37.03961445Z app=edgex-export-client source=registration.go:97 msg="Failed to query all registrations. Error: ERR unknown command `RANGE`, with args beginning with: `exportConfiguration`, `0`, `-1`, "
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:** Master / Fuji

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by FelixTing**
fix #2064

"RANGE" -> "ZRANGE"
"REVRANGE" -> "ZREVRANGE"

Signed-off-by: Felix Ting <felix@iotechsys.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
Requested review from @AnthonyMBonafide  as he was the one to last change that code (and potentially introduced the regression).

**Comment by AnthonyMBonafide** [comment]
I think this is what we intended on doing as part of PR #1741. However, those changes got reverted during some code clean up.

**Comment by tsconn23** [comment]
@FelixTing A PR on the Fuji branch is also required in order for the fix to be included in the release.

**Comment by michaelestrin** [comment]
@FelixTing 

Please rebase.
Please create separate pull request targeting fuji branch (and reference here).  

Based on @AnthonyMBonafide's prior approval, will merge when both of the above requests are completed.

**Pull request merged**
