### PR TITLE
fix(security): Replace abandoned JWT package

### LINKED ISSUE #3728: Replace abandoned github.com/dgrijalva/jwt-go
https://github.com/dgrijalva/jwt-go

THIS REPOSITORY IS NO LONGER MAINTANED
The new repository can be found at: https://github.com/golang-jwt/jwt

Recommended upgrade to https://github.com/golang-jwt/jwt
-

### PR DESCRIPTION
**Pull request by bnevis-i**
Closes #3728

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)  Dependency change only
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) N/A

## Testing Instructions
```sh
# in edgex-go
make docker
#in edgex-compose
cd compose-builder
make run dev
make get-token
```

## New Dependency Instructions (If applicable)
    Total increase in new imports: 0
    Does the new import introduce additional import dependencies, if so, how many? 0
    Releases/Tags: 17
    Contributors: 66
    License - what is the license, and is it Apache 2.0 compatible? MIT
    Stars/Forks/Watchers: 986/68/14
    godoc.org metrics: 170

This is a basic code hygene PR to replace an unmaintained package with a maintained one.

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
recheck

**Comment by bnevis-i** [comment]
@jim-wang-intel forgot to update Attribution.txt

**Review by lenny-intel — CHANGES_REQUESTED** [review]
LGTM, but we need to add the new module added to the approved list which I think Jim White has be requiring TSC vote??

**Comment by jpwhitemn** [comment]
New v4 of https://github.com/golang-jwt/jwt library upgrade
Per https://wiki.edgexfoundry.org/display/FA/Vetting+Process+for+3rd+Party+Dependencies#VettingProcessfor3rdPartyDependencies-ProcessResearch, here is the data
Release: 17 releases
Contributors:  66
License:  MIT
Stars: 987
Forks:  68
Watchers: 14
Imported by 171 (per godoc.org)
older version has been abandoned

**Comment by bnevis-i** [comment]
> older version has been abandoned

The older version is github.com/dgrijalva/jwt-go which had a deprecation banner on README put up 3 months ago.

**Review by jim-wang-intel — DISMISSED** [review]

**Comment by jpwhitemn** [comment]
Needs one test by someone - otherwise approved by TSC 9/29

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
```console
$ make get-token
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzMwMTUzMjYsImlhdCI6MTYzMzAxMTcyNiwiaXNzIjoiNTE0ZjQyN2YtNDg5Ni00OTkyLWE3M2UtYWRhNjhkM2FlOWQyIiwibmJmIjoxNjMzMDExNzI2fQ.(redacted)
$ export BEARER="Authorization: Bearer (above)"
$ curl -ki -H "$BEARER" https://localhost:8443/core-data/api/v2/ping
HTTP/2 200 
content-type: application/json
content-length: 62
x-correlation-id: 
date: Thu, 30 Sep 2021 14:23:51 GMT
x-kong-upstream-latency: 1
x-kong-proxy-latency: 32
via: kong/2.5.1

{"apiVersion":"v2","timestamp":"Thu Sep 30 14:23:51 UTC 2021"}
```

**Comment by bnevis-i** [comment]
Test case passed.  Had to rework some code because now that staticcheck is implemented, it caught use of a deprecated struct.

**Review by jim-wang-intel — APPROVED** [review]

**Pull request merged**
