### PR TITLE
feat!: Switch UOM file to YAML format

### LINKED ISSUE #4441: [Core Metadata] Switch UOM file to YAML format
# 🚀 Tech Debt

### Relevant Package [**REQUIRED**]

 This feature request is for Core Metadata

### Description [**REQUIRED**]
The UoM file is currently expected to be in TOML format. 
It was decide in Minnesota planning that all TOML files would be change to be YAML format.

### Describe the solution you'd like
The UoM file expected to be YAML format

### Describe alternatives you've considered
None

### PR DESCRIPTION
**Pull request by weichou1229**
It was decided in Minnesota planning that all TOML files would be change to be YAML format.

Close #4441

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) not impact
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) not impact
  <link to docs PR>

## Testing Instructions

- Run the service and check the YAML file is loaded
- Run unit test

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
@weichou1229 it's a breaking change.  please add `!` to commit message and PR title

**Comment by weichou1229** [comment]
> @weichou1229 it's a breaking change. please add `!` to commit message and PR title

Updated.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
