### PR TITLE
Use the same version for all commands

### PR DESCRIPTION
**Pull request by feclare**
Use the same version for all the components. 
Moved the version file to the root.

### CODE REVIEW

**Comment by feclare** [comment]
Improved a bit more the version handling. I added a version.go file in the root directory which each package can access to read the version.

Maybe the string "master" could be manually changed to the correct version when a tag is created.

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by feclare** [comment]
recheck

**Comment by feclare** [comment]
recheck

**Comment by feclare** [comment]
recheck

**Comment by feclare** [comment]
recheck

**Comment by feclare** [comment]
recheck

**Comment by feclare** [comment]
recheck

**Pull request merged**
