### PR TITLE
feat(security): Add secret store config for delayed start

### PR DESCRIPTION
**Pull request by bnevis-i**
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
In compose scripts, `make run delayed-start`

### CODE REVIEW

**Comment by bnevis-i** [comment]
@jpwhitemn Example of the boilerplate for delayed start services
@jim-wang-intel Please make sure I got this correct.

**Comment by jim-wang-intel** [comment]
> @jpwhitemn Example of the boilerplate for delayed start services @jim-wang-intel Please make sure I got this correct (do we want to default localhost like everything else?)

Format and naming-wise are correct; but i do have a question: do we need to make these configuration for all-core-services as I thought they don't do delayed-start (like core-data, for example)?

**Comment by bnevis-i** [comment]
> > @jpwhitemn Example of the boilerplate for delayed start services @jim-wang-intel Please make sure I got this correct (do we want to default localhost like everything else?)
> 
> @bnevis-i / @jpwhitemn : Format and naming-wise are correct; but i do have a question: do we need to make these configuration for all-core-services as I thought they don't do delayed-start (like core-data, for example)?

The point of the exercise is that we make the configuration visible, even if we don't intend to enable it at this point.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
