### PR TITLE
fix: Build docker images with proper names

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?
Some security services have wrong Docker image names

## What is the new behavior?
All service Docker image names match that built by the CI pipelines

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by jim-wang-intel — CHANGES_REQUESTED** [review]
still seeing error on `docker-compose up` for missing the docker image: `edgexfoundry/docker-security-bootstrap-redis-go`: that should also change the name too.  
Eg.: 
```makefile
edgexfoundry/docker-edgex-security-bootstrap-redis-go  -> edgexfoundry/docker-security-bootstrap-redis-go
```

**Review by jpwhitemn — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@jim-wang-intel , good catch!! Fixed. Please try again. 
Not sure why my test didn't catch it. My compose file may have been old. Got latest for sure now.

**Review by jim-wang-intel — APPROVED** [review]
yes, it works now:
```sh
jim@jim-NUC7i5DNHE:~/go/src/github.com/lenny-intel/edgex-go$ docker ps
CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS                                                                                                NAMES
8a5e1d3418f5        emqx/kuiper:1.0.0-alpine                                               "/usr/bin/docker-ent…"   40 seconds ago      Up 38 seconds       127.0.0.1:20498->20498/tcp, 9081/tcp, 127.0.0.1:48075->48075/tcp                                     edgex-kuiper
02bbefa206f4        edgexfoundry/docker-sys-mgmt-agent-go:0.0.0-dev                        "/sys-mgmt-agent -cp…"   42 seconds ago      Up 39 seconds       127.0.0.1:48090->48090/tcp                                                                           edgex-sys-mgmt-agent
92ef93260d24        nexus3.edgexfoundry.org:10004/docker-app-service-configurable:master   "/app-service-config…"   43 seconds ago      Up 40 seconds       48095/tcp, 127.0.0.1:48100->48100/tcp                                                                edgex-app-service-configurable-rules
e38e3f5ebfc9        edgexfoundry/docker-core-command-go:0.0.0-dev                          "/core-command -cp=c…"   44 seconds ago      Up 41 seconds       127.0.0.1:48082->48082/tcp                                                                           edgex-core-command
2aef9fb80e6e        edgexfoundry/docker-core-data-go:0.0.0-dev                             "/core-data -cp=cons…"   44 seconds ago      Up 42 seconds       127.0.0.1:5563->5563/tcp, 127.0.0.1:48080->48080/tcp                                                 edgex-core-data
e7cd24acfc49        edgexfoundry/docker-core-metadata-go:0.0.0-dev                         "/core-metadata -cp=…"   45 seconds ago      Up 44 seconds       127.0.0.1:48081->48081/tcp                                                                           edgex-core-metadata
68d573650b77        edgexfoundry/docker-support-notifications-go:0.0.0-dev                 "/support-notificati…"   48 seconds ago      Up 45 seconds       127.0.0.1:48060->48060/tcp                                                                           edgex-support-notifications
3d3f9d413f09        edgexfoundry/docker-support-scheduler-go:0.0.0-dev                     "/support-scheduler …"   48 seconds ago      Up 46 seconds       127.0.0.1:48085->48085/tcp                                                                           edgex-support-scheduler
1a476d0d90b9        edgexfoundry/docker-security-bootstrap-redis-go:0.0.0-dev              "/entrypoint.sh"         50 seconds ago      Up 48 seconds                                                                                                            edgex-security-bootstrap-database
6c9b5668efaa        edgexfoundry/docker-security-secretstore-setup-go:0.0.0-dev            "entrypoint.sh"          51 seconds ago      Up 49 seconds                                                                                                            edgex-vault-worker
25a1f099c403        kong:2.0.5                                                             "/docker-entrypoint.…"   53 seconds ago      Up 52 seconds       0.0.0.0:8000->8000/tcp, 127.0.0.1:8001->8001/tcp, 0.0.0.0:8443->8443/tcp, 127.0.0.1:8444->8444/tcp   kong
f0990320822c        vault:1.5.3                                                            "/vault/init/start_v…"   56 seconds ago      Up 51 seconds       127.0.0.1:8200->8200/tcp                                                                             edgex-vault
0454d2ae7d4d        redis:6.0.9-alpine                                                     "docker-entrypoint.s…"   58 seconds ago      Up 56 seconds       127.0.0.1:6379->6379/tcp                                                                             edgex-redis
e70a6d8e6a84        nexus3.edgexfoundry.org:10004/docker-edgex-consul:master               "edgex-consul-entryp…"   58 seconds ago      Up 55 seconds       8300-8302/tcp, 8400/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 127.0.0.1:8500->8500/tcp                 edgex-core-consul
7fac4c8f4f8e        postgres:12.3-alpine                                                   "docker-entrypoint.s…"   58 seconds ago      Up 54 seconds       127.0.0.1:5432->5432/tcp                                                                             kong-db
```

**Pull request merged**
