### PR TITLE
refactor: Rename Encode func to better name

### PR DESCRIPTION
**Pull request by lenny-intel**
Function also writes response.

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **N/A for name refactoring**
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?) **N/A for name refactoring**
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A for name refactoring**

## Testing Instructions
**N/A for name refactoring**

## New Dependency Instructions (If applicable)
**N/A for name refactoring**

### CODE REVIEW

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Review by weichou1229 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
