### PR TITLE
fix(security): core-command fuzzing test http error 500

### PR DESCRIPTION
**Pull request by vli11**
fixed fuzzing core-command http error 500 when invalid input in body http://localhost:59882/api/v3/device/name/Random-Boolean-Device/Bool

Closes: #4639

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?) just updated the unit test
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
make docker-fuzz
make fuzz-test-command
1. after fuzz test is finished, open "/edgex-go/fuzz_test/fuzz_results/core-command/FuzzLean/RestlerResults/experiment113/bug_buckets", you should not see checker_500 error logs.
2. go back to edge-go, run `make test`, everything should pass

or you can verify it on postman:
PUT http://localhost:59882/api/v3/device/name/Random-Boolean-Device/Bool
raw JSON "false" into the body
output should not be 500 error, here is the expected output:
{
    "apiVersion": "v3",
    "message": "failed to parse request body",
    "statusCode": 400
}

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cloudxxx8 , FYI, this fixes the status code return for invalid input which was triggering many fuzzing failures as it deems a Internal Server error (500) as a failure. In general we should never be returning Internal Server error (500) unless unavoidable, like expected element is missing, stability issues, etc.

**Review by jim-wang-intel — APPROVED** [review]

**Comment by bnevis-i** [comment]
> @cloudxxx8 , FYI, this fixes the status code return for invalid input which was triggering many fuzzing failures as it deems a Internal Server error (500) as a failure. In general we should never be returning Internal Server error (500) unless unavoidable, like expected element is missing, stability issues, etc.

To be more specific, HTTP 500 means the web server was incapable of fulfilling the request.  Like out of memory, out of disk, 2+2=5, etc.  Everything else that is detectable should be in the 4xx error range.  For example, AWS returns HTTP 400 (Bad Request) with specific error codes in their JSON responses.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
You are right.  The original error code was wrong.

**Pull request merged**
