### PR TITLE
Fix support-notifications was failing to send email for critical notification.

### PR DESCRIPTION
**Pull request by akramtexas**
- This PR addresses: #2041 
- This fix is for the `Fuji` branch, and was made possible by invaluable assist from @tsconn23, and also @michaelestrin, and @AnthonyMBonafide 👍

### CODE REVIEW

**Comment by akramtexas** [comment]
got-critical-notif-email
- Successfully-generated email as ⬆️ 
- Associated logging as follows:
```
level=INFO ts=2019-11-11T19:45:09.917803Z app=edgex-support-notifications source=rest_subscription.go:69 msg="Posting Subscription: {\"slug\":\"sys-admin\",\"receiver\":\"System Administrator\",\"subscribedCategories\":[\"HW_HEALTH\"],\"subscribedLabels\":[\"temperature\",\"humidity\"],\"channels\":[{\"type\":\"REST\",\"url\":\"http://35d5d4d4.ngrok.io/alert\"},{\"type\":\"EMAIL\",\"mailAddresses\":[\"sftwr4040@gmail.com\"]}]}"
```

**Comment by akramtexas** [comment]
- Details specific to the fix (to the `Dockerfile` can be found here: [Comment in related Issue](https://github.com/edgexfoundry/edgex-go/issues/2041#issuecomment-552541656).

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
Recheck

**Comment by tsconn23** [comment]
This PR contains the expected change. Awaiting @jinlinGuan 's validation.

**Comment by akramtexas** [comment]
I have `rebased` the feature branch (build checks now running), following the approval of PR by @jinlinGuan.

**Pull request merged**
