### PR TITLE
Fix security-api-gateway config file (for master)

### LINKED ISSUE #1458: Kong in snap doesn't use correct certificate anymore
With the recent changes to the security-api-gateway configuration.toml file the following sed expression no longer replaces the tokenpath correctly:

https://github.com/edgexfoundry/edgex-go/blob/9316aae57bf09fc6e089f7042539513ea2da8a54/snap/snapcraft.yaml#L976-L977

Because the upstream edinburgh branch configuration.toml file for security-api-gateway changed to no longer contain the `admin-token.json` we are trying to replace:

https://github.com/edgexfoundry/security-api-gateway/blob/96482b5a8dbee3213916b39e23d37dd61c08bdda/core/res/configuration.toml#L43

This means that `edgexproxy` is unable to load the certificates we generate for Kong from `pkisetup` for Kong to use when hosting HTTPS endpoints

I will send a patch shortly for this, we should include it in Edinburgh

### PR DESCRIPTION
**Pull request by anonymouse64**
Forward-port to master of #1459 

Fixes #1458 for master/Fuji

### CODE REVIEW

**Comment by tsconn23** [comment]
recheck

**Comment by anonymouse64** [comment]
recheck

**Comment by anonymouse64** [comment]
Ah there is actually a breakage here with the snap (but nothing to do with this PR):
```
16:41:03 install: cannot stat 'core/edgexproxy': No such file or directory
```

I assume this is because of the newly merged changes to security-api-gateway on master.

@tsconn23 @mkbhanda how soon is the transition to edgex-go going to happen? If it's not going to happen for a few weeks I'll fix it here in the meantime, but if it's gonna switch soon I'll just let it be  because we will need to rewrite it for the transition to edgex-go anyways

**Comment by mkbhanda** [comment]
I encountered this issue too blackbox testing .. was wondering if I pulled before merge, but pulled after Jim sent out message of release.
Tingyu

**Comment by tsconn23** [comment]
@anonymouse64 
> @tsconn23 @mkbhanda how soon is the transition to edgex-go going to happen?
Could take some time, Ian. Work hasn't even started yet.

**Comment by anonymouse64** [comment]
This PR now handles the new master branch layout of security-api-gateway and, in addition to fixing the config file for #1458 will also unbreak all the currently broken stage-snap master jobs in Jenkins.

**Comment by anonymouse64** [comment]
recheck

**Pull request closed without merging**
