### PR TITLE
#318 Logging submodule under support module missed a Attribution.txt file

### PR DESCRIPTION
**Pull request by yanghua**
Signed-off-by: yanghua <yanghua1127@gmail.com>

cc @tsconn23

### CODE REVIEW

**Comment by yanghua** [comment]
@tsconn23 is the __edgex-go-verify__ blocking?

**Comment by feclare** [comment]
recheck

**Comment by yanghua** [comment]
@feclare and @tsconn23 this PR failed~

**Comment by tsconn23** [comment]
recheck

**Comment by drasko** [comment]
@tsconn23 I think this one is good for merging.

**Comment by tsconn23** [comment]
@yanghua Just rebase your branch to clear the "out-of-date" message above and I'll pull this in.

**Comment by yanghua** [comment]
cc @tsconn23

**Pull request merged**
